PROJECT_VERSION = 0.0.0

CODE_PKG_VERSION = $(PROJECT_VERSION)

CONTAINER_OS_VERSION = focal
CONTAINER_OS_VERSION_NUMBER = 20.04
CONTAINER_OS_BUILD_NUMBER = 20201106
CONTAINER_IMAGE_TAG = dev
CONTAINER_IBM_ART_VERSION = 1.5.0
CONTAINER_MINICONDA_VERSION = 4.9.2
CONTAINER_PYTHON_VERSION = 3.7.*
CONTAINER_SPHINX_VERSION = 3.3.1
CONTAINER_MLFLOW_VERSION = 1.12.1
CONTAINER_PREFECT_VERSION = 0.13.19
CONTAINER_PYTORCH_VERSION = 1.7.1
CONTAINER_SKLEARN_VERSION = 0.22.2
CONTAINER_TENSORFLOW2_VERSION = 2.1.0
