load:
  load_artifacts_for_job:
    job_id: $job_id
    extract_files: [$adv_tar_name]

dataset:
  load_dataset:
    ep_seed: $seed
    training_dir: $training_dir
    testing_dir: $training_dir
    subsets: ['testing']
    image_size: $image_size
    rescale: $rescale
    batch_size: $batch_size
    shuffle: False
  dependencies:
    - load

model:
  create_model:
    dataset: $dataset.testing
    model_architecture: $model_architecture
    input_shape: $model_input_size
    learning_rate: $learning_rate
    optimizer: $optimizer_name
    metrics_list:
      - name: CategoricalAccuracy
        parameters: { name: accuracy }
      - name: Precision
        parameters: { name: precision }
      - name: Recall
        parameters: { name: recall }
      - name: AUC
        parameters: { name: auc }
  dependencies:
    - dataset

cleanlab:
  clean:
    classifier: $model
    dataset: $dataset.testing
  dependencies:
    - model

save:
  save_artifacts_and_models:
    artifacts:
      - type: dataframe
        data_frame: $cleanlab.issuefiles_crossval
        file_name: "ds_remove.csv"
        file_format: "csv"
        file_format_kwargs:
  dependencies:
    - cleanlab