artifacts:
  defended_dataset:
    contents: $def_data_dir
    task:
      name: DirectoryArtifactTask
  distance_metrics:
    contents: $defended
    task:
      name: DataframeArtifactTask
      args:
        format: csv

graph:
  dataset:
    load_dataset:
      ep_seed: $seed
      testing_dir: $adversarial_dataset
      batch_size: $batch_size
      subsets: [testing]
      image_size: $image_size
      rescale: $rescale
      shuffle: False

  model: 
    read_model:
      location: $model_file
      art: true
      classifier_kwargs:
        clip_values: $clip_values

  # model:
  #   load_model:
  #     model_name: $model_name
  #     model_version: $model_version
  #     art: true
  #     classifier_kwargs:
  #       clip_values: $clip_values

  defended:
    augment_data:
      dataset: $dataset.testing
      def_data_dir: $def_data_dir
      image_size: $image_size
      batch_size: $batch_size
      def_type: $def_type
      defense_kwargs: $defense_kwargs
      distance_metrics:
        - name: l_infinity_norm
          func: l_inf_norm
        - name: l_1_norm
          func: l_1_norm
        - name: l_2_norm
          func: l_2_norm
        - name: cosine_similarity
          func: paired_cosine_similarities
        - name: euclidean_distance
          func: paired_euclidean_distances
        - name: manhattan_distance
          func: paired_manhattan_distances
        - name: wasserstein_distance
          func: paired_wasserstein_distances