load:
  load_artifacts_for_job:
    job_id: $job_id
    files: ['ds_remove.csv']

dataset:
  load_dataset:
    ep_seed: $seed
    training_dir: $training_dir
    testing_dir: $training_dir
    subsets: ['testing']
    image_size: $image_size
    rescale: $rescale
    batch_size: $batch_size
    shuffle: False

parse:
  parse_csv: 
    csv_file: $load
  dependencies:
    - load

filtering:
  filter_data:
    dataset: $dataset.testing
    delete_idxs: $parse
    clean_data_dir: $clean_data_dir
    save: True
    batch_size: $batch_size
  dependencies:
    - parse
    - dataset

save:
  save_artifacts_and_models:
    artifacts:
      - type: tarball
        adv_data_dir: $clean_data_dir
        adv_tar_name: $clean_tar_name
  dependencies:
    - filtering