dataset:
  load_dataset:
    ep_seed: $seed
    testing_dir: $data_dir
    subsets: [testing]
    image_size: $image_size
    batch_size: $batch_size
    rescale: $rescale

model:
  load_model:
    model_name: $model_name
    model_version: $model_version
    art: true
    image_size: $image_size
    classifier_kwargs:
      clip_values: $clip_values


gen_patches:
  attack_patch:
    data_flow: $dataset.testing
    adv_data_dir: $adv_data_dir
    model: $model
    patch_target: $patch_target
    num_patch: $num_patch
    num_patch_samples: $batch_size
    rotation_max: $rotation_max
    scale_min: $scale_min
    scale_max: $scale_max
    learning_rate: $learning_rate
    max_iter: $max_iter

save:
  save_artifacts_and_models:
    artifacts:
      - type: tarball
        adv_data_dir: $adv_data_dir
        adv_tar_name: $adv_tar_name
  dependencies:
    - gen_patches