dataset:
  load_dataset:
    ep_seed: $seed
    testing_dir: $poison_dir
    subsets: [testing]
    image_size: $image_size
    batch_size: $batch_size
    rescale: $rescale
    shuffle: False

model:
  load_model:
    model_name: $model_name
    model_version: $model_version
    art: true
    classifier_kwargs:
      clip_values: $clip_values

poisoning:
  poison:
    dataset: $dataset.testing
    classifier: $model
    percentage: $percent_poison
    adv_data_dir: $adv_data_dir
    batch_size: $batch_size
    target_idx: $target_idx
    eps: $eps
    eps_step: $eps_step
    max_iter: $max_iter
    clean_label: $clean_label
  dependencies:
    - model

save:
  save_artifacts_and_models:
    artifacts:
      - type: tarball
        adv_data_dir: $adv_data_dir
        adv_tar_name: $adv_tar_name
  dependencies:
    - poisoning