dataset:
  load_dataset:
    ep_seed: $seed
    testing_dir: $poison_dir
    subsets: [training, testing]
    image_size: $image_size
    batch_size: $batch_size
    rescale: $rescale
    shuffle: False

model:
  create_model:
    dataset: $dataset.training
    model_architecture: $model_architecture
    input_shape: $image_size
    learning_rate: $learning_rate
    optimizer: $optimizer_name
    metrics_list:
      - name: CategoricalAccuracy
        parameters: { name: accuracy }
      - name: Precision
        parameters: { name: precision }
      - name: Recall
        parameters: { name: recall }
      - name: AUC
        parameters: { name: auc }
  dependencies:
    - dataset

poisoning:
  poison:
    dataset: $dataset.testing
    classifier: $model
    percentage: $percent_poison
    adv_data_dir: $adv_data_dir
    batch_size: $batch_size
    target_idx: $target_idx
    eps: $eps
    eps_step: $eps_step
    nb_epochs: $nb_epochs
    max_iter: $max_iter
    clean_label: $clean_label
  dependencies:
    - model

save:
  save_artifacts_and_models:
    artifacts:
      - type: tarball
        adv_data_dir: $adv_data_dir
        adv_tar_name: $adv_tar_name
  dependencies:
    - poisoning