artifacts:
  predictions:
    contents: $predictions
    task:
      name: dataframe
      args:
        format: csv

graph:
  dataset:
    load_dataset:
      ep_seed: $seed
      testing_dir: $dataset
      subsets: [testing]
      image_size: $image_size
      batch_size: $batch_size
      rescale: $rescale
      shuffle: False
    dependencies:
      - load

  model:
    load_model:
      model_name: $model_name
      model_version: $model_version

  predictions:
    predict:
      classifier: $model
      dataset: $dataset.testing
      show_actual: $record_actual_class
      show_target: $record_target_class
    dependencies:
      - model

