load:
  load_artifacts_for_job:
    job_id: $job_id
    extract_files: [$tar_name]

dataset:
  load_dataset:
    ep_seed: $seed
    testing_dir: $data_dir
    subsets: [testing]
    image_size: $image_size
    batch_size: $batch_size

model:
  load_model:
    model_name: $model_name
    model_version: $model_version

predictions:
  predict:
    classifier: $model
    dataset: $dataset.testing
    show_actual: $record_actual_class
    show_target: $record_target_class
  dependencies:
    - model

save:
  save_artifacts_and_models:
    artifacts:
      - type: dataframe
        data_frame: $predictions
        file_name: $filename
        file_format: $format
        file_format_kwargs:
  dependencies:
    - predictions