"""empty message

Revision ID: b2ff2e33852f
Revises: 
Create Date: 2020-09-09 13:22:42.657507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b2ff2e33852f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("last_modified", sa.DateTime(), nullable=True),
        sa.Column(
            "queue",
            sa.Enum("tensorflow_cpu", "tensorflow_gpu", name="jobqueue"),
            nullable=True,
        ),
        sa.Column("timeout", sa.Text(), nullable=True),
        sa.Column("workflow_uri", sa.Text(), nullable=True),
        sa.Column("entry_point", sa.Text(), nullable=True),
        sa.Column("entry_point_kwargs", sa.Text(), nullable=True),
        sa.Column("depends_on", sa.String(length=36), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "queued", "started", "deferred", "finished", "failed", name="jobstatus"
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_index(op.f("ix_jobs_queue"), "jobs", ["queue"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_queue"), table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
