load:
  ?load:
    load_artifacts_for_job:
      job_id: $job_id
      extract_files: [$adv_tar_name]
    passthrough:

dataset:
  load_dataset:
    ep_seed: $seed
    testing_dir: $input_dir
    batch_size: $batch_size
    subsets: [testing]
    image_size: $image_size
    rescale: $rescale
    shuffle: False
  dependencies:
    - load

model:
  load_model:
    model_name: $model_name
    model_version: $model_version
    art: true
    classifier_kwargs:
      clip_values: $clip_values

transformed:
  ?transform_data:
    augment_data:
      dataset: $dataset.testing
      def_data_dir: $output_dir
      image_size: $image_size
      batch_size: $batch_size
      def_type: $def_type
      defense_kwargs: $transform_kwargs
      distance_metrics:
        - name: l_infinity_norm
          func: l_inf_norm
        - name: l_1_norm
          func: l_1_norm
        - name: l_2_norm
          func: l_2_norm
        - name: cosine_similarity
          func: paired_cosine_similarities
        - name: euclidean_distance
          func: paired_euclidean_distances
        - name: manhattan_distance
          func: paired_manhattan_distances
        - name: wasserstein_distance
          func: paired_wasserstein_distances
    attack_fgm:
      dataset: $dataset.testing
      adv_data_dir: $output_dir
      classifier: $model
      batch_size: $batch_size
      eps: $eps
      eps_step: $eps_step
      minimal: $minimal
      norm: $norm
      distance_metrics:
        - name: l_infinity_norm
          func: l_inf_norm
        - name: l_1_norm
          func: l_1_norm
        - name: l_2_norm
          func: l_2_norm
        - name: cosine_similarity
          func: paired_cosine_similarities
        - name: euclidean_distance
          func: paired_euclidean_distances
        - name: manhattan_distance
          func: paired_manhattan_distances
        - name: wasserstein_distance
          func: paired_wasserstein_distances
    attack_patch:
      data_flow: $dataset.testing
      adv_data_dir: $output_dir
      model: $model
      patch_target: $patch_target
      num_patch: $num_patch
      num_patch_samples: $batch_size
      rotation_max: $rotation_max
      scale_min: $scale_min
      scale_max: $scale_max
      learning_rate: $learning_rate
      max_iter: $max_iter
      patch_shape: $patch_shape
    augment_patch:
      data_flow: $dataset.testing
      adv_data_dir: $output_dir
      patch_dir: $patch_dir
      model: $model
      patch_shape: $patch_shape
      distance_metrics:
        - name: l_infinity_norm
          func: l_inf_norm
        - name: l_1_norm
          func: l_1_norm
        - name: l_2_norm
          func: l_2_norm
        - name: cosine_similarity
          func: paired_cosine_similarities
        - name: euclidean_distance
          func: paired_euclidean_distances
        - name: manhattan_distance
          func: paired_manhattan_distances
        - name: wasserstein_distance
          func: paired_wasserstein_distances
      batch_size: $batch_size
      patch_scale: $patch_scale
      rotation_max: $rotation_max
      scale_min: $scale_min
      scale_max: $scale_max
    passthrough_dataset:
      dataset: $dataset

save:
  save_artifacts_and_models:
    artifacts:
      - type: tarball
        adv_data_dir: $def_data_dir
        adv_tar_name: $def_tar_name
      - type: dataframe
        data_frame: $transformed
        file_name: $distance_metrics_filename
        file_format: csv.gz
        file_format_kwargs:
          index: false