# This Software (Dioptra) is being made available as a public service by the
# National Institute of Standards and Technology (NIST), an Agency of the United
# States Department of Commerce. This software was developed in part by employees of
# NIST and in part by NIST contractors. Copyright in portions of this software that
# were developed by NIST contractors has been licensed or assigned to NIST. Pursuant
# to Title 17 United States Code Section 105, works of NIST employees are not
# subject to copyright protection in the United States. However, NIST may hold
# international copyright in software created by its employees and domestic
# copyright (or licensing rights) in portions of software that were assigned or
# licensed to NIST. To the extent that NIST holds copyright in this software, it is
# being made available under the Creative Commons Attribution 4.0 International
# license (CC BY 4.0). The disclaimers of the CC BY 4.0 license apply to all parts
# of the software developed or licensed by NIST.
#
# ACCESS THE FULL CC BY 4.0 LICENSE HERE:
# https://creativecommons.org/licenses/by/4.0/legalcode
from typing import Final, Generic, Protocol, TypeVar

from .artifacts import ArtifactsCollectionClient
from .auth import AuthCollectionClient
from .base import (
    DioptraResponseProtocol,
    DioptraSession,
    JsonObject,
    JsonObjectList,
    JsonValue,
)
from .drafts import (
    ModifyResourceDraftsSubCollectionClient,
    NewResourceDraftsSubCollectionClient,
)
from .entrypoints import EntrypointsCollectionClient
from .experiments import ExperimentsCollectionClient
from .groups import GroupsCollectionClient
from .jobs import JobsCollectionClient
from .models import ModelsCollectionClient
from .plugin_parameter_types import PluginParameterTypesCollectionClient
from .plugins import PluginsCollectionClient
from .queues import QueuesCollectionClient
from .snapshots import SnapshotsSubCollectionClient
from .tags import TagsCollectionClient
from .users import UsersCollectionClient
from .workflows import WorkflowsCollectionClient

DIOPTRA_V1_ROOT: Final[str]
ENV_DIOPTRA_API: Final[str]

T = TypeVar("T")

class QueueTagsJsonSubCollectionClientProtocol(Protocol):
    def get(self, *resource_ids: str | int) -> JsonObjectList: ...
    def modify(self, *resource_ids: str | int, ids: list[int]) -> JsonObjectList: ...
    def append(self, *resource_ids: str | int, ids: list[int]) -> JsonObjectList: ...
    def remove(self, *resource_ids: str | int, tag_id: int) -> JsonObject: ...
    def remove_all(self, *resource_ids: str | int) -> JsonObject: ...

class QueuesJsonCollectionClientProtocol(Protocol):
    @property
    def new_resource_drafts(
        self,
    ) -> NewResourceDraftsSubCollectionClient[JsonValue]: ...
    @property
    def modify_resource_drafts(
        self,
    ) -> ModifyResourceDraftsSubCollectionClient[JsonValue]: ...
    @property
    def snapshots(self) -> SnapshotsSubCollectionClient[JsonValue]: ...
    @property
    def tags(self) -> QueueTagsJsonSubCollectionClientProtocol: ...
    def get(
        self,
        group_id: int | None = None,
        index: int = 0,
        page_length: int = 10,
        sort_by: str | None = None,
        descending: bool | None = None,
        search: str | None = None,
        show_deleted: bool | None = None,
    ) -> JsonObject: ...
    def get_by_id(self, queue_id: str | int) -> JsonObject: ...
    def create(
        self,
        group_id: int,
        name: str,
        description: str | None = None,
    ) -> JsonObject: ...
    def modify_by_id(
        self,
        queue_id: str | int,
        name: str,
        description: str | None,
    ) -> JsonObject: ...
    def delete_by_id(self, queue_id: str | int) -> JsonObject: ...

class DioptraClient(Generic[T]):
    def __init__(self, session: DioptraSession[T]) -> None: ...
    @property
    def users(self) -> UsersCollectionClient[T]: ...
    @property
    def auth(self) -> AuthCollectionClient[T]: ...
    @property
    def queues(self) -> QueuesCollectionClient[T]: ...
    @property
    def tags(self) -> TagsCollectionClient[T]: ...
    @property
    def groups(self) -> GroupsCollectionClient[T]: ...
    @property
    def plugins(self) -> PluginsCollectionClient[T]: ...
    @property
    def plugin_parameter_types(self) -> PluginParameterTypesCollectionClient[T]: ...
    @property
    def experiments(self) -> ExperimentsCollectionClient[T]: ...
    @property
    def jobs(self) -> JobsCollectionClient[T]: ...
    @property
    def entrypoints(self) -> EntrypointsCollectionClient[T]: ...
    @property
    def models(self) -> ModelsCollectionClient[T]: ...
    @property
    def artifacts(self) -> ArtifactsCollectionClient[T]: ...
    @property
    def workflows(self) -> WorkflowsCollectionClient[T]: ...
    def close(self) -> None: ...

class ResponseDioptraClientProtocol(Protocol):
    @property
    def users(self) -> UsersCollectionClient[DioptraResponseProtocol]: ...
    @property
    def auth(self) -> AuthCollectionClient[DioptraResponseProtocol]: ...
    @property
    def queues(self) -> QueuesCollectionClient[DioptraResponseProtocol]: ...
    @property
    def tags(self) -> TagsCollectionClient[DioptraResponseProtocol]: ...
    @property
    def groups(self) -> GroupsCollectionClient[DioptraResponseProtocol]: ...
    @property
    def plugins(self) -> PluginsCollectionClient[DioptraResponseProtocol]: ...
    @property
    def plugin_parameter_types(
        self,
    ) -> PluginParameterTypesCollectionClient[DioptraResponseProtocol]: ...
    @property
    def experiments(self) -> ExperimentsCollectionClient[DioptraResponseProtocol]: ...
    @property
    def jobs(self) -> JobsCollectionClient[DioptraResponseProtocol]: ...
    @property
    def entrypoints(self) -> EntrypointsCollectionClient[DioptraResponseProtocol]: ...
    @property
    def models(self) -> ModelsCollectionClient[DioptraResponseProtocol]: ...
    @property
    def artifacts(self) -> ArtifactsCollectionClient[DioptraResponseProtocol]: ...
    @property
    def workflows(self) -> WorkflowsCollectionClient[DioptraResponseProtocol]: ...
    def close(self) -> None: ...

class JsonDioptraClientProtocol(Protocol):
    @property
    def users(self) -> UsersCollectionClient[JsonValue]: ...
    @property
    def auth(self) -> AuthCollectionClient[JsonValue]: ...
    @property
    def queues(self) -> QueuesJsonCollectionClientProtocol: ...
    @property
    def tags(self) -> TagsCollectionClient[JsonValue]: ...
    @property
    def groups(self) -> GroupsCollectionClient[JsonValue]: ...
    @property
    def plugins(self) -> PluginsCollectionClient[JsonValue]: ...
    @property
    def plugin_parameter_types(
        self,
    ) -> PluginParameterTypesCollectionClient[JsonValue]: ...
    @property
    def experiments(self) -> ExperimentsCollectionClient[JsonValue]: ...
    @property
    def jobs(self) -> JobsCollectionClient[JsonValue]: ...
    @property
    def entrypoints(self) -> EntrypointsCollectionClient[JsonValue]: ...
    @property
    def models(self) -> ModelsCollectionClient[JsonValue]: ...
    @property
    def artifacts(self) -> ArtifactsCollectionClient[JsonValue]: ...
    @property
    def workflows(self) -> WorkflowsCollectionClient[JsonValue]: ...
    def close(self) -> None: ...

def connect_response_dioptra_client(
    address: str | None = None,
) -> ResponseDioptraClientProtocol: ...
def connect_json_dioptra_client(
    address: str | None = None,
) -> JsonDioptraClientProtocol: ...
def _build_api_address(address: str | None) -> str: ...
