types:
  callback:
  dataloader:
  directoryiterator:
  functiontype:
  kerasclassifier:
  metric:
  mlflowrun:
  tuple:
  model:
  modelversion:
  np.ndarray:
  optimizer:
  path:
  dataframe:
  rngenerator:
  sequential:
  tarfile:
  list_callback:
    list: callback
  list_tuple_string_any:
    list: tuple_string_any
  list_union_metric_functiontype:
    list: union_metric_functiontype
  list_union_string_path:
    list: union_string_path
  list_mapping_string_string:
    list: mapping_string_string
  list_mapping_string_any:
    list: mapping_string_any
  mapping_string_any:
    mapping: [string, any]
  mapping_string_mapping_string_any:
    mapping: [string, mapping_string_any]
  list_mapping_string_mapping_string_any:
    list: mapping_string_mapping_string_any
  mapping_string_number:
    mapping: [string, number]
  mapping_string_string:
    mapping: [string, string]
  tuple_integer_integer:
    tuple: [integer, integer]
  tuple_integer_integer_integer:
    tuple: [integer, integer, integer]
  tuple_string_any:
    tuple: [string, any]
  union_integer_number_string:
    union: [integer, number, string]
  union_integer_any:
    union: [integer, any]
  union_metric_functiontype:
    union: [metric, functiontype]
  union_null_list_tuple_string_any:
    union: [list_tuple_string_any , "null"]
  union_null_mapping_string_any:
    union: [mapping_string_any, "null"]
  union_null_modelversion:
    union: [modelversion, "null"]
  union_null_number:
    union: [number, "null"]
  union_null_string:
    union: [string, "null"]
  union_null_union_integer_any:
    union: [union_integer_any, "null"]
  union_string_path:
    union: [string, path]
  union_null_union_string_path:
    union: [union_string_path, "null"]
parameters:
  training_dir: /dioptra/data/Mnist/training
  testing_dir: /dioptra/data/Mnist/testing
  image_size: [28, 28, 1]
  adv_tar_name: adversarial_poison.tar.gz
  adv_data_dir: adv_poison_data
  model_name: ""
  model_version: 1
  batch_size: 32
  imagenet_preprocessing: false
  target_index: 0
  eps: 50
  eps_step: 0.1
  norm: 2
  seed: -1
  label_type: test

tasks:
  init_rng:
    plugin: dioptra_builtins.random.rng.init_rng
    inputs:
      - name: seed
        type: integer
        required: false
    outputs:
      - seed: integer
      - rng: rngenerator

  draw_random_integer:
    plugin: dioptra_builtins.random.sample.draw_random_integer
    inputs:
      - rng: rngenerator
      - name: low
        type: integer
        required: false
      - name: high
        type: integer
        required: false
    outputs:
      value: integer

  init_tensorflow:
    inputs:
    - seed: integer
    plugin: dioptra_builtins.backend_configs.tensorflow.init_tensorflow

  make_directories:
    inputs:
    - dirs: list_union_string_path
    plugin: dioptra_builtins.artifacts.utils.make_directories

  log_parameters:
    plugin: dioptra_builtins.tracking.mlflow.log_parameters
    inputs:
      - parameters: mapping_string_number

  get_distance_metric_list:
    plugin: dioptra_builtins.metrics.distance.get_distance_metric_list
    inputs:
      - request: list_mapping_string_string
    outputs:
      distance_metrics_list: list_tuple_string_any

  create_adversarial_clean_poison_dataset:
    inputs:
    - data_dir: string
    - adv_data_dir: union_string_path
    - keras_classifier: kerasclassifier
    - image_size: tuple_integer_integer_integer
    - name: distance_metrics_list
      required: false
      type: union_null_list_tuple_string_any
    - name: rescale
      required: false
      type: number
    - name: batch_size
      required: false
      type: integer
    - name: label_mode
      required: false
      type: string
    - name: eps
      required: false
      type: number
    - name: eps_step
      required: false
      type: number
    - name: max_iter
      required: false
      type: integer
    - name: norm
      required: false
      type: number
    - name: label_type
      required: false
      type: string
    - name: poison_fraction
      required: false
      type: number
    - name: target_index
      required: false
      type: integer
    outputs:
      ret: dataframe
    plugin: dioptra_custom.custom_poisoning_plugins.attacks_poison.create_adversarial_clean_poison_dataset
  select_rescale_value:
    inputs:
    - imagenet_preprocessing: boolean
    outputs:
      ret: number
    plugin: dioptra_custom.custom_poisoning_plugins.datasetup.select_rescale_value
  select_clip_values:
    inputs:
    - image_size: tuple_integer_integer_integer
    outputs:
      ret: tuple_integer_integer
    plugin: dioptra_custom.custom_poisoning_plugins.datasetup.select_clip_values

  upload_directory_as_tarball_artifact:
    plugin: dioptra_builtins.artifacts.mlflow.upload_directory_as_tarball_artifact
    inputs:
      - source_dir: union_string_path
      - tarball_filename: string
      - name: tarball_write_mode
        type: string
        required: false
      - name: working_dir
        type: union_null_union_string_path
        required: false
  upload_data_frame_artifact:
    plugin: dioptra_builtins.artifacts.mlflow.upload_data_frame_artifact
    inputs:
      - data_frame: dataframe
      - file_name: string
      - file_format: string
      - name: file_format_kwargs
        type: union_null_mapping_string_any
        required: false
      - name: working_dir
        type: union_null_union_string_path
        required: false
  load_wrapped_tensorflow_keras_classifier:
    inputs:
    - name: name
      type: string
    - version: integer
    - name: clip_values
      required: false
      type: tuple_integer_integer
    - name: imagenet_preprocessing
      required: false
      type: boolean
    outputs:
      ret: kerasclassifier
    plugin: dioptra_builtins.registry.art.load_wrapped_tensorflow_keras_classifier

  prepend_cwd:
    plugin:
     dioptra_custom.evaluation.mlflow.prepend_cwd
    inputs:
      - path: string
    outputs: 
      ret: string

graph:
  init_rng:
    init_rng: $seed

  tensorflow_global_seed:
    draw_random_integer: $init_rng.rng
    
  dataset_seed:
    draw_random_integer: $init_rng.rng

  init_tensorflow_results:
    init_tensorflow: $tensorflow_global_seed

  adv_data_dir_path:
    prepend_cwd: $adv_data_dir
      
  make_directories_results:
    make_directories: [[$adv_data_dir_path]]

  rescale:
    select_rescale_value: $imagenet_preprocessing
  clip_values:
    select_clip_values: $image_size

  log_mlflow_params_result:
    log_parameters:
      - entry_point_seed: $seed
        tensorflow_global_seed: $tensorflow_global_seed
        dataset_seed: $dataset_seed
        rescale: $rescale

  keras_classifier:
    load_wrapped_tensorflow_keras_classifier:
      name: $model_name
      version: $model_version
      imagenet_preprocessing: $imagenet_preprocessing
      classifier_kwargs:
        clip_values: $clip_values
    dependencies: init_tensorflow_results

  distance_metrics_list:
    get_distance_metric_list:
      - - name: l_infinity_norm
          func: l_inf_norm
        - name: l_1_norm
          func: l_1_norm
        - name: l_2_norm
          func: l_2_norm
        - name: cosine_similarity
          func: paired_cosine_similarities
        - name: euclidean_distance
          func: paired_euclidean_distances
        - name: manhattan_distance
          func: paired_manhattan_distances
        - name: wasserstein_distance
          func: paired_wasserstein_distances

  distance_metrics:
    create_adversarial_clean_poison_dataset:
      data_dir: $testing_dir
      distance_metrics_list: $distance_metrics_list
      adv_data_dir: $adv_data_dir_path
      image_size: $image_size
      keras_classifier: $keras_classifier
      rescale: $rescale
      label_type: $label_type
      batch_size: $batch_size
      eps: $eps
      eps_step: $eps_step
      norm: $norm
      target_index: $target_index
    dependencies: [make_directories_results]
    
  log_evasion_dataset_result:
    upload_directory_as_tarball_artifact:
      source_dir: $adv_data_dir_path
      tarball_filename: $adv_tar_name
    dependencies: [distance_metrics]
  log_distance_metrics_result:
    upload_data_frame_artifact:
      - $distance_metrics
      - distance_metrics.csv
      - csv.gz
      - index: false
