types:
  callback:
  dataloader:
  directoryiterator:
  functiontype:
  kerasclassifier:
  metric:
  mlflowrun:
  model:
  modelversion:
  tuple:
  np.ndarray:
  optimizer:
  path:
  dataframe:
  rngenerator:
  sequential:
  tarfile:
  list_tuple_string_any:
    list: tuple_string_any
  list_union_metric_functiontype:
    list: union_metric_functiontype
  list_union_string_path:
    list: union_string_path
  list_mapping_string_string:
    list: mapping_string_string
  mapping_string_any:
    mapping: [string, any]
  mapping_string_number:
    mapping: [string, number]
  mapping_string_string:
    mapping: [string, string]
  tuple_integer_integer:
    tuple: [integer, integer]
  tuple_integer_integer_integer:
    tuple: [integer, integer, integer]
  tuple_string_any:
    tuple: [string, any]
  union_integer_number_string:
    union: [integer, number, string]
  union_integer_any:
    union: [integer, any]
  union_metric_functiontype:
    union: [metric, functiontype]
  union_null_list_tuple_string_any:
    union: [list_tuple_string_any , "null"]
  union_null_mapping_string_any:
    union: [mapping_string_any, "null"]
  union_null_modelversion:
    union: [modelversion, "null"]
  union_null_number:
    union: [number, "null"]
  union_null_string:
    union: [string, "null"]
  union_null_union_integer_any:
    union: [union_integer_any, "null"]
  union_string_path:
    union: [string, path]
  union_null_union_string_path:
    union: [union_string_path, "null"]

parameters:
  data_dir: /dioptra/data/
  image_size: [28, 28, 1]
  run_id: 08xz
  model: mnist_le_net
  model_architecture: le_net
  bit_depth: 8
  adv_tar_name: testing_adversarial_fgm.tar.gz
  adv_data_dir: adv_testing
  model_version: 1
  batch_size: 32
  seed: -1
tasks: 
  init_rng:
    inputs:
      - name: seed
        required: false
        type: integer
    outputs:
      - seed: integer
      - rng: rngenerator
    plugin: dioptra_builtins.random.rng.init_rng
  draw_random_integer:
    inputs:
      - rng: rngenerator
      - name: low
        required: false
        type: integer
      - name: high
        required: false
        type: integer
    outputs:
      ret: integer
    plugin: dioptra_builtins.random.sample.draw_random_integer
  init_tensorflow:
    inputs:
      - seed: integer
    plugin: dioptra_builtins.backend_configs.tensorflow.init_tensorflow
  make_directories:
    inputs:
      - dirs: list_union_string_path
    plugin: dioptra_builtins.artifacts.utils.make_directories
  log_parameters:
    inputs:
      - parameters: mapping_string_number
    plugin: dioptra_builtins.tracking.mlflow.log_parameters
  get_distance_metric_list:
    plugin: dioptra_builtins.metrics.distance.get_distance_metric_list
    inputs:
      - request: list_mapping_string_string
    outputs:
      distance_metrics_list: list_tuple_string_any
  download_all_artifacts_in_run:
    plugin: dioptra_builtins.artifacts.mlflow.download_all_artifacts_in_run
    inputs:
      - run_id: string
      - artifact_path: string
      - name: destination_path
        type: union_null_string
        required: false
    outputs:
      ret: string
  extract_tarfile:
    plugin: dioptra_builtins.artifacts.utils.extract_tarfile
    inputs:
      - filepath: union_string_path
      - name: tarball_read_mode
        type: string
        required: false
      - name: output_dir
        type: any
        required: false
  create_image_dataset:
    inputs:
      - data_dir: string
      - subset: union_null_string
      - image_size: tuple_integer_integer_integer
      - seed: integer
      - name: rescale
        required: false
        type: number
      - name: validation_split
        required: false
        type: union_null_number
      - name: batch_size
        required: false
        type: integer
      - name: label_mode
        required: false
        type: string
    outputs:
      ret: directoryiterator
    plugin: dioptra_builtins.data.tensorflow.create_image_dataset
  feature_squeeze:
    inputs:
      - data_dir: string
      - run_id: string
      - model: string
      - model_architecture: string
      - adv_tar_name: string
      - image_size: tuple_integer_integer_integer
      - adv_data_dir: string
      - data_flow: directoryiterator
      - name: batch_size
        required: false
        type: integer
      - name: seed
        required: false
        type: integer
      - name: bit_depth
        required: false
        type: integer
      - name: model_version
        required: false
        type: integer
    plugin: dioptra_custom.feature_squeezing.squeeze_plugin.feature_squeeze
  prepend_cwd:
    plugin:
      dioptra_custom.evaluation.mlflow.prepend_cwd
    inputs:
      - path: string
    outputs: 
      ret: string
graph:
  init_rng:
    init_rng: $seed

  tensorflow_global_seed:
    draw_random_integer: $init_rng.rng

  dataset_seed:
    draw_random_integer: $init_rng.rng

  init_tensorflow_results:
    init_tensorflow: $tensorflow_global_seed

  adv_data_path:
    prepend_cwd: $adv_data_dir

  make_directories_results:
    make_directories: [[$adv_data_path]]

  make_directories_results:
    make_directories: [[def_testing]]

  log_mlflow_params_result:
    log_parameters:
      - entry_point_seed: $seed
        tensorflow_global_seed: $tensorflow_global_seed
        dataset_seed: $dataset_seed

  distance_metrics_list:
    get_distance_metric_list:
      - - name: l_infinity_norm
          func: l_inf_norm
        - name: l_1_norm
          func: l_1_norm
        - name: l_2_norm
          func: l_2_norm
        - name: cosine_similarity
          func: paired_cosine_similarities
        - name: euclidean_distance
          func: paired_euclidean_distances
        - name: manhattan_distance
          func: paired_manhattan_distances
        - name: wasserstein_distance
          func: paired_wasserstein_distances

  adv_tar_path:
    download_all_artifacts_in_run:
      run_id: $run_id
      artifact_path: $adv_tar_name
  
  extract_tarfile_results:
    extract_tarfile:
      filepath: $adv_tar_path
  
  adv_ds:
    create_image_dataset:
      data_dir: $adv_data_dir
      subset:
      validation_split:
      image_size: $image_size
      seed: $dataset_seed
    dependencies: [make_directories_results, extract_tarfile_results]

  feature_squeeze:
    feature_squeeze:
      data_dir: $data_dir
      model: $model
      model_version: $model_version
      model_architecture: $model_architecture
      batch_size: $batch_size
      seed: $seed
      bit_depth: $bit_depth
      run_id: $run_id
      adv_tar_name: $adv_tar_name
      adv_data_dir: $adv_data_dir
      data_flow: $adv_ds
      image_size: $image_size
    dependencies: [make_directories_results]
