types:
  rng:
  optimizer:
  name_parameters:
    mapping:
      name: string
      parameters:
        mapping: [string, any]
  metrics_list:
    list: 
      mapping:
        name: string
        parameters:
          mapping: [string, any]
  performance_metrics:
  metrics:
  callbacks_in:
    list: 
      mapping:
        name: string
        parameters:
          mapping: [string, any]
  callbacks_out:
    mapping:
      name: string
      parameters:
        mapping: [string, any]
  directory_iterator:
  parameters:
    mapping: [string, number]
  image_size:
    tuple: [integer, integer, integer]
  sequential:
  fit_kwargs:
    mapping: [string, any]
  fit_kwargs_null:
    union:
      - mapping: [string, any]
      - "null"
  str_null:
    union: [string, "null"]
  num_null:
    union: [number, "null"]

parameters:
  seed_p: -1
  optimizer_name: Adam
  learning_rate_p: 0.001
  training_dir: /dioptra/data/Mnist/training
  testing_dir: /dioptra/data/Mnist/testing
  image_size_p: [28, 28, 1]
  validation_split_p: 0.2
  batch_size_p: 32
  model_architecture: le_net
  epochs_p: 30
  register_model_name: ""

tasks:
  init_rng:
    plugin: dioptra_custom.vc.random_rng.init_rng
    inputs:
      - name: seed
        type: integer
        required: false
    outputs:
      - ret1: integer
      - ret2: rng

  draw_random_integer:
    plugin: dioptra_custom.vc.random_sample.draw_random_integer
    inputs:
      - rng: rng
      - name: low
        type: integer
        required: false
      - name: high
        type: integer
        required: false
    outputs:
      value: integer

  init_tensorflow:
    plugin: dioptra_custom.vc.backend_configs_tensorflow.init_tensorflow
    inputs:
      - seed: integer

  log_parameters:
    plugin: dioptra_custom.vc.tracking_mlflow.log_parameters
    inputs:
      - parameters: parameters

  get_optimizer:
    plugin: dioptra_custom.vc.tensorflow.get_optimizer
    inputs:
      - name: optimizer
        type: string
      - learning_rate: number
    outputs:
      optimizer: optimizer

  get_performance_metrics:
    plugin: dioptra_custom.vc.tensorflow.get_performance_metrics
    inputs:
      - metrics_list: metrics_list
    outputs:
      performance_metrics: performance_metrics

  get_model_callbacks:
    plugin: dioptra_custom.vc.tensorflow.get_model_callbacks
    inputs:
      - callbacks_list: callbacks_in
    outputs:
      callbacks: callbacks_out

  create_image_dataset:
    plugin: dioptra_custom.vc.data_tensorflow.create_image_dataset
    inputs:
      - data_dir: string
      - subset: str_null
      - image_size: image_size
      - seed: integer
      - name: rescale
        type: number
        required: false
      - name: validation_split
        type: num_null
        required: false
      - name: batch_size
        type: integer
        required: false
      - name: label_mode
        type: string
        required: false
    outputs:
      dataset: directory_iterator

  get_n_classes_from_directory_iterator:
    plugin: dioptra_custom.vc.data_tensorflow.get_n_classes_from_directory_iterator
    inputs:
      - ds: directory_iterator
    outputs:
      num_classes: integer

  init_classifier:
    plugin: dioptra_custom.vc.estimators_keras_classifiers.init_classifier
    inputs:
      - model_architecture: string
      - optimizer: optimizer
      - metrics: performance_metrics
      - input_shape: image_size
      - n_classes: integer
      - name: loss
        type: string
        required: false
    outputs:
      classifier: sequential

  fit:
    plugin: dioptra_custom.vc.estimators_methods.fit
    inputs:
      - estimator: any
      - x: any
      - name: y
        type: any
        required: false
      - name: fit_kwargs
        type: fit_kwargs_null
        required: false

  evaluate_metrics_tensorflow:
    plugin: dioptra_custom.vc.tensorflow.evaluate_metrics_tensorflow
    inputs:
      - classifier: sequential
      - dataset: directory_iterator
    outputs:
      metrics: metrics

  log_metrics:
    plugin: dioptra_custom.vc.tracking_mlflow.log_metrics
    inputs:
      - metrics: metrics

  log_tensorflow_keras_estimator:
    plugin: dioptra_custom.vc.tracking_mlflow.log_tensorflow_keras_estimator
    inputs:
      - estimator: sequential
      - model_dir: string

  add_model_to_registry:
    plugin: dioptra_custom.vc.mlflow.add_model_to_registry
    inputs:
      - name: name
        type: string
      - model_dir: string
  get_none:
    plugin: dioptra_custom.vc.tensorflow.get_none
    inputs:
      - arg: string
    outputs:
      ret: "null"
  process_float:
    plugin: dioptra_custom.vc.tensorflow.process_float
    inputs:
        - arg: string
    outputs:
      ret: number
  process_int:
    plugin: dioptra_custom.vc.tensorflow.process_int
    inputs:
        - arg: string
    outputs:
      ret: integer
  process_int_list:
    plugin: dioptra_custom.vc.tensorflow.process_int_list
    inputs:
      - arg: string
    outputs:
      ret: image_size
      
graph:
  batch_size:
    process_int: $batch_size_p

  epochs:
    process_int: $epochs_p

  validation_split:
    process_float: $validation_split_p

  true_none:
    get_none: 'h'

  image_size:
    process_int_list: $image_size_p

  learning_rate:
    process_float: $learning_rate_p

  seed:
    process_int: $seed_p
    
  init_rng:
    init_rng: $seed

  global_seed:
    draw_random_integer:
      rng: $init_rng.ret2

  dataset_seed:
    draw_random_integer:
      rng: $init_rng.ret2

  init_tensorflow:
    init_tensorflow: $global_seed

  log_params:
    log_parameters:
      - entry_point_seed: $init_rng.ret1
        tensorflow_global_seed: $global_seed
        dataset_seed: $dataset_seed

  optimizer:
    get_optimizer: 
      optimizer: $optimizer_name
      learning_rate: $learning_rate
    dependencies:
      - init_tensorflow

  perf_metrics:
    get_performance_metrics:
      - - name: CategoricalAccuracy
          parameters: { name: accuracy }
        - name: Precision
          parameters: { name: precision }
        - name: Recall
          parameters: { name: recall }
        - name: AUC
          parameters: { name: auc }
    dependencies:
      - init_tensorflow

  callbacks:
    get_model_callbacks:
      - - name: EarlyStopping
          parameters:
            monitor: val_loss
            min_delta: .01
            patience: 5
            restore_best_weights: true
    dependencies:
      - init_tensorflow

  training_dataset:
    create_image_dataset:
      data_dir: $training_dir
      subset: training
      image_size: $image_size
      seed: $dataset_seed
      validation_split: $validation_split
      batch_size: $batch_size
    dependencies:
      - init_tensorflow

  validation_dataset:
    create_image_dataset:
      data_dir: $training_dir
      subset: validation
      image_size: $image_size
      seed: $dataset_seed
      validation_split: $validation_split
      batch_size: $batch_size
    dependencies:
      - init_tensorflow

  testing_dataset:
    create_image_dataset:
      data_dir: $testing_dir
      subset: null
      image_size: $image_size
      seed: $dataset_seed
      validation_split: null
      batch_size: $batch_size
    dependencies:
      - init_tensorflow

  num_classes:
    get_n_classes_from_directory_iterator: $training_dataset

  classifier:
    init_classifier:
      model_architecture: $model_architecture
      optimizer: $optimizer
      metrics: $perf_metrics
      input_shape: $image_size
      n_classes: $num_classes
    dependencies:
      - init_tensorflow

  model:
    fit:
      estimator: $classifier
      x: $training_dataset
      fit_kwargs:
        nb_epochs: $epochs
        validation_data: $validation_dataset
        callbacks: $callbacks
        verbose: 2

  eval_metrics_tensorflow:
    evaluate_metrics_tensorflow:
      - $classifier
      - $testing_dataset
    dependencies:
      - model

  log_metrics:
    log_metrics: $eval_metrics_tensorflow

  log_keras_estimator:
    log_tensorflow_keras_estimator:
      - $classifier
      - model
    dependencies:
      - model

  add_model_to_registry:
    add_model_to_registry:
      - $register_model_name
      - model
    dependencies:
      - log_keras_estimator
