"""Add Job-Swaps ORM
Address issue #823 to create Job-Swaps ORM
https://github.com/usnistgov/dioptra/issues/823


Revision ID: 0353e16317eb
Revises: ad4f89b2288d
Create Date: 2026-06-15 18:58:15.395141

"""
import sqlalchemy as sa
from alembic import op

SWAPS_TABLE_NAME="job_swaps"


# revision identifiers, used by Alembic.
revision = '0353e16317eb'
down_revision = 'ad4f89b2288d'
branch_labels = None
depends_on = None


def upgrade():
    """ Creates job_swaps ORM-mapped table and links it to the existing entities
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(SWAPS_TABLE_NAME,
    sa.Column('job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('swap_name', sa.Text(), nullable=False),
    sa.Column('task_alias', sa.Text(), nullable=False),
    sa.Column('plugin_file_resource_snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),

    # FK - constraints to add   
    sa.ForeignKeyConstraint(['job_id'], ['jobs.resource_id'], name=op.f('fk_job_swaps_job_id_jobs')),
    sa.ForeignKeyConstraint(['plugin_file_resource_snapshot_id'], ['plugin_files.resource_snapshot_id'], name=op.f('fk_job_swaps_plugin_file_resource_snapshot_id_plugin_files')),

    # PK - constraints to add   
    sa.PrimaryKeyConstraint('job_id', 'task_alias', 'plugin_file_resource_snapshot_id', name=op.f('pk_job_swaps'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(SWAPS_TABLE_NAME)
    # ### end Alembic commands ###
