"""Revise fields in job logging table

Revision ID: 06e8176155bf
Revises: d5330f35d77e
Create Date: 2025-08-15 16:25:10.196160

"""
import datetime
from typing import Annotated

from alembic import op
import sqlalchemy as sa
from dioptra.restapi.db.custom_types import TZDateTime

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    MappedAsDataclass,
    mapped_column,
    sessionmaker,
)

# revision identifiers, used by Alembic.
revision = '06e8176155bf'
down_revision = 'd5330f35d77e'
branch_labels = None
depends_on = None


# database dialects
POSTGRES_DIALECT = "postgresql"

# table names
JOB_LOGS = "job_logs"


# Migration data models
intpk = Annotated[
    int,
    mapped_column(sa.BigInteger().with_variant(sa.Integer, "sqlite"), primary_key=True),
]
bigint = Annotated[
    int, mapped_column(sa.BigInteger().with_variant(sa.Integer, "sqlite"))
]
datetimetz = Annotated[datetime.datetime, mapped_column(TZDateTime())]
text_ = Annotated[str, mapped_column(sa.Text())]
bool_ = Annotated[bool, mapped_column(sa.Boolean())]


class UpgradeBase(DeclarativeBase, MappedAsDataclass):
    pass


class DowngradeBase(DeclarativeBase, MappedAsDataclass):
    pass


class JobLogUpgrade(UpgradeBase):
    __tablename__ = JOB_LOGS

    # Database fields
    id: Mapped[intpk]
    job_resource_id: Mapped[bigint]
    severity: Mapped[text_]
    message: Mapped[text_]
    step_name: Mapped[text_]
    timestamp: Mapped[datetimetz]
    logger_name: Mapped[text_]
    created_on: Mapped[datetimetz]


class JobLogDowngrade(DowngradeBase):
    __tablename__ = JOB_LOGS

    # Database fields
    id: Mapped[intpk]
    job_resource_id: Mapped[bigint]
    severity: Mapped[text_]
    message: Mapped[text_]
    step_name: Mapped[text_]
    timestamp: Mapped[datetimetz]
    logger_name: Mapped[text_]
    created_on: Mapped[datetimetz]


def get_sessionmaker():
    bind = op.get_bind()
    return sessionmaker(bind=bind)


def get_database_dialect():
    return op.get_context().dialect.name


# BEGIN: Upgrade
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_job_logs_table()
    migrate_data_upgrade()
    set_non_nullable_columns_in_job_logs_table_upgrade()
    drop_obsolete_columns_from_job_logs_table()
    # ### end Alembic commands ###


# Upgrade Functions
def migrate_data_upgrade():
    Session = get_sessionmaker()
    with Session() as session:
        migrate_job_logs_upgrade(session)

        session.commit()


def migrate_job_logs_upgrade(session):
    stmt = sa.select(JobLogUpgrade)

    for job_log in session.scalars(stmt):
        job_log.created_on = job_log.timestamp
        job_log.logger_name = job_log.step_name if job_log.step_name else "dioptra"


def update_job_logs_table():
    with op.batch_alter_table(JOB_LOGS, schema=None) as batch_op:
        batch_op.add_column(sa.Column('logger_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_on', TZDateTime(), nullable=True))


def set_non_nullable_columns_in_job_logs_table_upgrade():
    with op.batch_alter_table(JOB_LOGS, schema=None) as batch_op:
        batch_op.alter_column('logger_name', nullable=False)
        batch_op.alter_column('created_on', nullable=False)


def drop_obsolete_columns_from_job_logs_table():
    with op.batch_alter_table(JOB_LOGS, schema=None) as batch_op:
        batch_op.drop_column('step_name')
        batch_op.drop_column('timestamp')


# BEGIN: Downgrade
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    restore_columns_dropped_from_job_logs_table()
    migrate_data_downgrade()
    set_non_nullable_columns_in_job_logs_table_downgrade()
    revert_job_logs_table()
    # ### end Alembic commands ###


# Downgrade Functions
def migrate_data_downgrade():
    Session = get_sessionmaker()
    with Session() as session:
        migrate_job_logs_downgrade(session)

        session.commit()


def migrate_job_logs_downgrade(session):
    stmt = sa.select(JobLogDowngrade)

    for job_log in session.scalars(stmt):
        job_log.step_name = job_log.logger_name
        job_log.timestamp = job_log.created_on


def restore_columns_dropped_from_job_logs_table():
    with op.batch_alter_table(JOB_LOGS, schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('step_name', sa.TEXT(), nullable=True))


def set_non_nullable_columns_in_job_logs_table_downgrade():
    with op.batch_alter_table(JOB_LOGS, schema=None) as batch_op:
        batch_op.alter_column('timestamp', nullable=False)


def revert_job_logs_table():
    with op.batch_alter_table(JOB_LOGS, schema=None) as batch_op:
        batch_op.drop_column('created_on')
        batch_op.drop_column('logger_name')
