"""Add JobSwaps ORM

Revision ID: 30e74c5564b3
Revises: ad4f89b2288d
Create Date: 2026-06-16 10:17:21.101904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e74c5564b3'
down_revision = 'ad4f89b2288d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_swaps',
    sa.Column('job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('swap_name', sa.Text(), nullable=False),
    sa.Column('task_alias', sa.Text(), nullable=False),
    sa.Column('plugin_file_resource_snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.resource_id'], name=op.f('fk_job_swaps_job_id_jobs')),
    sa.ForeignKeyConstraint(['plugin_file_resource_snapshot_id'], ['plugin_files.resource_snapshot_id'], name=op.f('fk_job_swaps_plugin_file_resource_snapshot_id_plugin_files')),
    sa.PrimaryKeyConstraint('job_id', 'swap_name', name=op.f('pk_job_swaps'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_swaps')
    # ### end Alembic commands ###
