"""add job logging table

Revision ID: d5330f35d77e
Revises: 0ca6eca33569
Create Date: 2025-06-05 21:27:08.623800

"""

import sqlalchemy as sa
from alembic import op

from dioptra.restapi.db.custom_types import TZDateTime

# revision identifiers, used by Alembic.
revision = "d5330f35d77e"
down_revision = "0ca6eca33569"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_log_severity",
        sa.Column("severity", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("severity", name=op.f("pk_job_log_severity")),
    )
    op.create_table(
        "job_logs",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "job_resource_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("step_name", sa.Text(), nullable=True),
        sa.Column("timestamp", TZDateTime(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_resource_id"],
            ["resources.resource_id"],
            name=op.f("fk_job_logs_job_resource_id_resources"),
        ),
        sa.ForeignKeyConstraint(
            ["severity"],
            ["job_log_severity.severity"],
            name=op.f("fk_job_logs_severity_job_log_severity"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_logs")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_logs")
    op.drop_table("job_log_severity")
    # ### end Alembic commands ###
