"""modifications to support artifact handling

Revision ID: fa39987673e0
Revises: 0ca6eca33569
Create Date: 2025-05-30 09:33:07.080834

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fa39987673e0"
down_revision = "0ca6eca33569"
branch_labels = None
depends_on = None

# table names
ARTIFACT_TASKS = "artifact_tasks"
ARTIFACTS = "artifacts"
ENTRY_POINT_ARTIFACT_OUTPUT_PARAMETERS = "entry_point_artifact_output_parameters"
ENTRY_POINT_ARTIFACT_PLUGINS = "entry_point_artifact_plugins"
ENTRY_POINT_ARTIFACT_VALUES = "entry_point_artifact_values"
ENTRY_POINT_ARTIFACTS = "entry_point_artifacts"
ENTRY_POINT_JOBS = "entry_point_jobs"
ENTRY_POINTS = "entry_points"
FUNCTION_TASKS = "function_tasks"
PLUGIN_PLUGIN_FILES = "plugin_plugin_files"
PLUGIN_TASK_INPUT_PARAMETERS = "plugin_task_input_parameters"
PLUGIN_TASK_OUTPUT_PARAMETERS = "plugin_task_output_parameters"
PLUGIN_TASK_PARAMETER_TYPES = "plugin_task_parameter_types"
PLUGIN_TASKS = "plugin_tasks"
PLUGINS = "plugins"
RESOURCES = "resources"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    create_artifact_tasks_table()
    create_entry_point_artifact_output_parameters_table()
    create_entry_point_artifact_plugins_table()
    create_entry_point_artifact_values_table()
    create_entry_point_artifacts_table()
    create_function_tasks_table()

    update_artifacts_table()
    update_entry_points_table()
    update_plugin_task_input_parameters_table()
    update_plugin_task_output_parameters_table()
    update_plugin_tasks_table()

    drop_obsolete_indexes_from_plugin_task_input_parameters_table()
    drop_obsolete_indexes_from_plugin_task_output_parameters_table()

    # Data migrations go here

    set_non_nullable_columns_in_artifacts_table_upgrade()
    set_non_nullable_columns_in_entry_points_table_upgrade()
    set_non_nullable_columns_in_plugin_task_input_parameters_table_upgrade()
    set_non_nullable_columns_in_plugin_task_output_parameters_table_upgrade()
    set_non_nullable_columns_in_plugin_tasks_table_upgrade()

    change_primary_key_for_plugin_task_input_parameters_table()
    change_primary_key_for_plugin_task_output_parameters_table()
    change_primary_key_for_plugin_tasks_table()

    drop_obsolete_columns_from_plugin_task_input_parameters_table()
    drop_obsolete_columns_from_plugin_task_output_parameters_table()

    add_indexes_to_entry_point_artifact_output_parameters_table()
    add_indexes_to_entry_point_artifact_values_table()
    add_indexes_to_entry_point_artifacts_table()
    add_indexes_to_plugin_tasks_table()

    add_foreign_keys_to_artifact_tasks_table()
    add_foreign_keys_to_artifacts_table()
    add_foreign_keys_to_entry_point_artifact_output_parameters_table()
    add_foreign_keys_to_entry_point_artifact_plugins_table()
    add_foreign_keys_to_entry_point_artifact_values_table()
    add_foreign_keys_to_entry_point_artifacts_table()
    add_foreign_keys_to_function_tasks_table()
    add_foreign_keys_to_plugin_task_input_parameters_table()
    add_foreign_keys_to_plugin_task_output_parameters_table()
    # ### end Alembic commands ###


# Upgrade Functions: plugin_task_output_parameters
def update_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        # "plugin_task_id" will become part of the new primary key after data migration
        # is complete
        batch_op.add_column(
            sa.Column(
                "plugin_task_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )


def set_non_nullable_columns_in_plugin_task_output_parameters_table_upgrade():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.alter_column("plugin_task_id", nullable=False)


def change_primary_key_for_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        # need to manually update the primary key
        batch_op.drop_constraint(
            batch_op.f(
                "fk_plugin_task_output_parameters_plugin_file_resource_snapshot_id_plugin_tasks"
            ),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            constraint_name=batch_op.f("pk_plugin_task_output_parameters"),
            type_="primary",
        )
        batch_op.create_primary_key(
            constraint_name=batch_op.f("pk_plugin_task_output_parameters"),
            columns=["plugin_task_id", "name"],
        )


def add_foreign_keys_to_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_plugin_task_output_parameters_plugin_task_id_plugin_tasks"),
            PLUGIN_TASKS,
            ["plugin_task_id"],
            ["task_id"],
        )


def drop_obsolete_columns_from_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_column("plugin_task_name")
        batch_op.drop_column("plugin_file_resource_snapshot_id")


def drop_obsolete_indexes_from_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_plugin_task_output_parameters_plugin_file_resource_snapshot_id"
            )
        )


# Upgrade Functions: plugin_task_input_parameters
def update_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        # "plugin_task_id" will become the new primary key after data migration is
        # complete
        batch_op.add_column(
            sa.Column(
                "plugin_task_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )


def set_non_nullable_columns_in_plugin_task_input_parameters_table_upgrade():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.alter_column("plugin_task_id", nullable=False)


def change_primary_key_for_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        # need to manually update the primary key
        batch_op.drop_constraint(
            batch_op.f(
                "fk_plugin_task_input_parameters_plugin_file_resource_snapshot_id_plugin_tasks"
            ),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            constraint_name=batch_op.f("pk_plugin_task_input_parameters"),
            type_="primary",
        )
        batch_op.create_primary_key(
            constraint_name=batch_op.f("pk_plugin_task_input_parameters"),
            columns=["plugin_task_id", "name"],
        )


def add_foreign_keys_to_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_plugin_task_input_parameters_plugin_task_id_plugin_tasks"),
            PLUGIN_TASKS,
            ["plugin_task_id"],
            ["task_id"],
        )


def drop_obsolete_columns_from_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_column("plugin_task_name")
        batch_op.drop_column("plugin_file_resource_snapshot_id")


def drop_obsolete_indexes_from_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_plugin_task_input_parameters_plugin_file_resource_snapshot_id"
            )
        )


# Upgrade Functions: plugin_tasks
def update_plugin_tasks_table():
    with op.batch_alter_table(PLUGIN_TASKS, schema=None) as batch_op:
        # "task_id" will become the new primary key after data migration is complete
        batch_op.add_column(
            sa.Column(
                "task_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )
        # Nullable will be set to False for "type" after data migration is complete
        batch_op.add_column(sa.Column("type", sa.String(), nullable=True))


def set_non_nullable_columns_in_plugin_tasks_table_upgrade():
    with op.batch_alter_table(PLUGIN_TASKS, schema=None) as batch_op:
        batch_op.alter_column("task_id", nullable=False)
        batch_op.alter_column("type", nullable=False)


def change_primary_key_for_plugin_tasks_table():
    with op.batch_alter_table(PLUGIN_TASKS, schema=None) as batch_op:
        # need to manually handle the addition of a new primary key -- perform after the
        # alter table to allow foreign key relationships to not break
        # creating the index above allows those relationships to continue
        batch_op.drop_constraint(
            constraint_name=batch_op.f("pk_plugin_tasks"), type_="primary"
        )
        batch_op.create_primary_key(
            constraint_name=batch_op.f("pk_plugin_tasks"), columns=["task_id"]
        )


def add_indexes_to_plugin_tasks_table():
    with op.batch_alter_table(PLUGIN_TASKS, schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_plugin_tasks_plugin_file_resource_snapshot_id"),
            ["plugin_file_resource_snapshot_id", "plugin_task_name"],
            unique=True,
        )


# Upgrade Functions: entry_points
def update_entry_points_table():
    with op.batch_alter_table(ENTRY_POINTS, schema=None) as batch_op:
        # Nullable will be set to False for "artifact_graph" after data migration is
        # complete
        batch_op.add_column(sa.Column("artifact_graph", sa.Text(), nullable=True))


def set_non_nullable_columns_in_entry_points_table_upgrade():
    with op.batch_alter_table(ENTRY_POINTS, schema=None) as batch_op:
        batch_op.alter_column("artifact_graph", nullable=False)


# Upgrade Functions: artifacts
def update_artifacts_table():
    with op.batch_alter_table(ARTIFACTS, schema=None) as batch_op:
        # Nullable will be set to False for "is_dir" after data migration is complete
        batch_op.add_column(sa.Column("is_dir", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("file_size", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "plugin_snapshot_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "plugin_file_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("task_name", sa.Text(), nullable=True))


def set_non_nullable_columns_in_artifacts_table_upgrade():
    with op.batch_alter_table(ARTIFACTS, schema=None) as batch_op:
        batch_op.alter_column("is_dir", nullable=False)


def add_foreign_keys_to_artifacts_table():
    with op.batch_alter_table(ARTIFACTS, schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_artifacts_plugin_file_id_plugin_tasks"),
            PLUGIN_TASKS,
            ["plugin_file_id", "task_name"],
            ["plugin_file_resource_snapshot_id", "plugin_task_name"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_artifacts_plugin_snapshot_id_plugin_plugin_files"),
            PLUGIN_PLUGIN_FILES,
            ["plugin_snapshot_id", "plugin_file_id"],
            ["plugin_resource_snapshot_id", "plugin_file_resource_snapshot_id"],
        )


# Upgrade Functions: entry_point_artifact_values
def create_entry_point_artifact_values_table():
    op.create_table(
        ENTRY_POINT_ARTIFACT_VALUES,
        sa.Column(
            "job_resource_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "entry_point_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "artifact_number",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "value",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "job_resource_id",
            "entry_point_resource_snapshot_id",
            "artifact_number",
            name=op.f("pk_entry_point_artifact_values"),
        ),
    )


def add_indexes_to_entry_point_artifact_values_table():
    with op.batch_alter_table(ENTRY_POINT_ARTIFACT_VALUES, schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entry_point_artifact_values_job_resource_id"),
            ["job_resource_id", "artifact_number"],
            unique=True,
        )


def add_foreign_keys_to_entry_point_artifact_values_table():
    with op.batch_alter_table(ENTRY_POINT_ARTIFACT_VALUES, schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_entry_point_artifact_values_entry_point_resource_snapshot_id_entry_point_artifacts"
            ),
            ENTRY_POINT_ARTIFACTS,
            ["entry_point_resource_snapshot_id", "artifact_number"],
            ["entry_point_resource_snapshot_id", "artifact_number"],
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_entry_point_artifact_values_entry_point_resource_snapshot_id_entry_point_jobs"
            ),
            ENTRY_POINT_JOBS,
            ["entry_point_resource_snapshot_id", "job_resource_id"],
            ["entry_point_resource_snapshot_id", "job_resource_id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_entry_point_artifact_values_job_resource_id_resources"),
            RESOURCES,
            ["job_resource_id"],
            ["resource_id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_entry_point_artifact_values_value_artifacts"),
            ARTIFACTS,
            ["value"],
            ["resource_snapshot_id"],
        )


# Upgrade Functions: function_tasks
def create_function_tasks_table():
    op.create_table(
        FUNCTION_TASKS,
        sa.Column(
            "function_task_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("function_task_id", name=op.f("pk_function_tasks")),
    )


def add_foreign_keys_to_function_tasks_table():
    with op.batch_alter_table(FUNCTION_TASKS, schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_function_tasks_function_task_id_plugin_tasks"),
            PLUGIN_TASKS,
            ["function_task_id"],
            ["task_id"],
        )


# Upgrade Functions: entry_point_artifact_output_parameters
def create_entry_point_artifact_output_parameters_table():
    op.create_table(
        ENTRY_POINT_ARTIFACT_OUTPUT_PARAMETERS,
        sa.Column(
            "entry_point_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "artifact_number",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "parameter_number",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "plugin_task_parameter_type_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint(
            "entry_point_resource_snapshot_id",
            "artifact_number",
            "parameter_number",
            "name",
            name=op.f("pk_entry_point_artifact_output_parameters"),
        ),
    )


def add_indexes_to_entry_point_artifact_output_parameters_table():
    with op.batch_alter_table(
        ENTRY_POINT_ARTIFACT_OUTPUT_PARAMETERS, schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f(
                "ix_entry_point_artifact_output_parameters_entry_point_resource_snapshot_id"
            ),
            ["entry_point_resource_snapshot_id", "artifact_number", "name"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f(
                "ix_entry_point_artifact_output_parameters_plugin_task_parameter_type_resource_snapshot_id"
            ),
            ["plugin_task_parameter_type_resource_snapshot_id"],
            unique=False,
        )


def add_foreign_keys_to_entry_point_artifact_output_parameters_table():
    with op.batch_alter_table(
        ENTRY_POINT_ARTIFACT_OUTPUT_PARAMETERS, schema=None
    ) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_entry_point_artifact_output_parameters_entry_point_resource_snapshot_id_entry_point_artifacts"
            ),
            ENTRY_POINT_ARTIFACTS,
            ["entry_point_resource_snapshot_id", "artifact_number"],
            ["entry_point_resource_snapshot_id", "artifact_number"],
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_entry_point_artifact_output_parameters_plugin_task_parameter_type_resource_snapshot_id_plugin_task_parameter_types"
            ),
            PLUGIN_TASK_PARAMETER_TYPES,
            ["plugin_task_parameter_type_resource_snapshot_id"],
            ["resource_snapshot_id"],
        )


# Upgrade Functions: artifact_tasks
def create_artifact_tasks_table():
    op.create_table(
        ARTIFACT_TASKS,
        sa.Column(
            "artifact_task_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("artifact_task_id", name=op.f("pk_artifact_tasks")),
    )


def add_foreign_keys_to_artifact_tasks_table():
    with op.batch_alter_table(ARTIFACT_TASKS, schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_artifact_tasks_artifact_task_id_plugin_tasks"),
            PLUGIN_TASKS,
            ["artifact_task_id"],
            ["task_id"],
        )


# Upgrade Functions: entry_point_artifacts
def create_entry_point_artifacts_table():
    op.create_table(
        ENTRY_POINT_ARTIFACTS,
        sa.Column(
            "entry_point_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "artifact_number",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint(
            "entry_point_resource_snapshot_id",
            "artifact_number",
            name=op.f("pk_entry_point_artifacts"),
        ),
    )


def add_indexes_to_entry_point_artifacts_table():
    with op.batch_alter_table(ENTRY_POINT_ARTIFACTS, schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entry_point_artifacts_entry_point_resource_snapshot_id"),
            ["entry_point_resource_snapshot_id", "name"],
            unique=True,
        )


def add_foreign_keys_to_entry_point_artifacts_table():
    with op.batch_alter_table(ENTRY_POINT_ARTIFACTS, schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_entry_point_artifacts_entry_point_resource_snapshot_id_entry_points"
            ),
            ENTRY_POINTS,
            ["entry_point_resource_snapshot_id"],
            ["resource_snapshot_id"],
        )


# Upgrade Functions: entry_point_artifact_plugins
def create_entry_point_artifact_plugins_table():
    op.create_table(
        ENTRY_POINT_ARTIFACT_PLUGINS,
        sa.Column(
            "entry_point_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "plugin_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "entry_point_resource_snapshot_id",
            "plugin_resource_snapshot_id",
            name=op.f("pk_entry_point_artifact_plugins"),
        ),
    )


def add_foreign_keys_to_entry_point_artifact_plugins_table():
    with op.batch_alter_table(ENTRY_POINT_ARTIFACT_PLUGINS, schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_entry_point_artifact_plugins_entry_point_resource_snapshot_id_entry_points"
            ),
            ENTRY_POINTS,
            ["entry_point_resource_snapshot_id"],
            ["resource_snapshot_id"],
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_entry_point_artifact_plugins_plugin_resource_snapshot_id_plugins"
            ),
            PLUGINS,
            ["plugin_resource_snapshot_id"],
            ["resource_snapshot_id"],
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    drop_foreign_keys_from_plugin_task_output_parameters_table()
    drop_foreign_keys_from_plugin_task_input_parameters_table()
    drop_foreign_keys_from_function_tasks_table()
    drop_foreign_keys_from_entry_point_artifacts_table()
    drop_foreign_keys_from_entry_point_artifact_values_table()
    drop_foreign_keys_from_entry_point_artifact_plugins_table()
    drop_foreign_keys_from_entry_point_artifact_output_parameters_table()
    drop_foreign_keys_from_artifacts_table()
    drop_foreign_keys_from_artifact_tasks_table()

    drop_indexes_from_plugin_tasks_table()
    drop_indexes_from_entry_point_artifacts_table()
    drop_indexes_from_entry_point_artifact_values_table()
    drop_indexes_from_entry_point_artifact_output_parameters_table()

    restore_columns_dropped_from_plugin_task_output_parameters_table()
    restore_columns_dropped_from_plugin_task_input_parameters_table()

    # Data migrations go here

    set_non_nullable_columns_in_plugin_task_output_parameters_table_downgrade()
    set_non_nullable_columns_in_plugin_task_input_parameters_table_downgrade()

    revert_primary_key_for_plugin_tasks_table()
    revert_primary_key_for_plugin_task_output_parameters_table()
    revert_primary_key_for_plugin_task_input_parameters_table()

    restore_indexes_dropped_from_plugin_task_output_parameters_table()
    restore_indexes_dropped_from_plugin_task_input_parameters_table()

    revert_plugin_tasks_table()
    revert_plugin_task_output_parameters_table()
    revert_plugin_task_input_parameters_table()
    revert_entry_points_table()
    revert_artifacts_table()

    drop_function_tasks_table()
    drop_entry_point_artifacts_table()
    drop_entry_point_artifact_values_table()
    drop_entry_point_artifact_plugins_table()
    drop_entry_point_artifact_output_parameters_table()
    drop_artifact_tasks_table()
    # ### end Alembic commands ###


# Downgrade Functions: plugin_task_output_parameters
def revert_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_column("plugin_task_id")


def revert_primary_key_for_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        # need to manually update the primary key
        batch_op.drop_constraint(
            constraint_name=batch_op.f("pk_plugin_task_output_parameters"),
            type_="primary",
        )
        batch_op.create_primary_key(
            constraint_name=batch_op.f("pk_plugin_task_output_parameters"),
            columns=["plugin_file_resource_snapshot_id", "plugin_task_name", "name"],
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_plugin_task_output_parameters_plugin_file_resource_snapshot_id_plugin_tasks"
            ),
            PLUGIN_TASKS,
            ["plugin_file_resource_snapshot_id", "plugin_task_name"],
            ["plugin_file_resource_snapshot_id", "plugin_task_name"],
        )


def drop_foreign_keys_from_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_plugin_task_output_parameters_plugin_task_id_plugin_tasks"),
            type_="foreignkey",
        )


def restore_columns_dropped_from_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("plugin_file_resource_snapshot_id", sa.INTEGER(), nullable=True)
        )
        batch_op.add_column(sa.Column("plugin_task_name", sa.TEXT(), nullable=True))


def restore_indexes_dropped_from_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f(
                "ix_plugin_task_output_parameters_plugin_file_resource_snapshot_id"
            ),
            ["plugin_file_resource_snapshot_id", "plugin_task_name", "name"],
            unique=1,
        )


def set_non_nullable_columns_in_plugin_task_output_parameters_table_downgrade():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.alter_column("plugin_file_resource_snapshot_id", nullable=False)
        batch_op.alter_column("plugin_task_name", nullable=False)


# Downgrade Functions: plugin_task_input_parameters
def revert_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_column("plugin_task_id")


def revert_primary_key_for_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        # need to manually update the primary key
        batch_op.drop_constraint(
            constraint_name=batch_op.f("pk_plugin_task_input_parameters"),
            type_="primary",
        )
        batch_op.create_primary_key(
            constraint_name=batch_op.f("pk_plugin_task_input_parameters"),
            columns=["plugin_file_resource_snapshot_id", "plugin_task_name", "name"],
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_plugin_task_input_parameters_plugin_file_resource_snapshot_id_plugin_tasks"
            ),
            PLUGIN_TASKS,
            ["plugin_file_resource_snapshot_id", "plugin_task_name"],
            ["plugin_file_resource_snapshot_id", "plugin_task_name"],
        )


def drop_foreign_keys_from_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_plugin_task_input_parameters_plugin_task_id_plugin_tasks"),
            type_="foreignkey",
        )


def restore_columns_dropped_from_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("plugin_file_resource_snapshot_id", sa.INTEGER(), nullable=True)
        )
        batch_op.add_column(sa.Column("plugin_task_name", sa.TEXT(), nullable=True))


def restore_indexes_dropped_from_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f(
                "ix_plugin_task_input_parameters_plugin_file_resource_snapshot_id"
            ),
            ["plugin_file_resource_snapshot_id", "plugin_task_name", "name"],
            unique=1,
        )


def set_non_nullable_columns_in_plugin_task_input_parameters_table_downgrade():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.alter_column("plugin_file_resource_snapshot_id", nullable=False)
        batch_op.alter_column("plugin_task_name", nullable=False)


# Downgrade Functions: plugin_tasks
def revert_plugin_tasks_table():
    with op.batch_alter_table(PLUGIN_TASKS, schema=None) as batch_op:
        batch_op.drop_column("type")
        batch_op.drop_column("task_id")


def revert_primary_key_for_plugin_tasks_table():
    with op.batch_alter_table(PLUGIN_TASKS, schema=None) as batch_op:
        # need to manually handle the change of the primary key
        batch_op.drop_constraint(
            constraint_name=batch_op.f("pk_plugin_tasks"), type_="primary"
        )
        batch_op.create_primary_key(
            constraint_name=batch_op.f("pk_plugin_tasks"),
            columns=["plugin_file_resource_snapshot_id", "plugin_task_name"],
        )


def drop_indexes_from_plugin_tasks_table():
    with op.batch_alter_table(PLUGIN_TASKS, schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_plugin_tasks_plugin_file_resource_snapshot_id")
        )


# Downgrade Functions: entry_points
def revert_entry_points_table():
    with op.batch_alter_table(ENTRY_POINTS, schema=None) as batch_op:
        batch_op.drop_column("artifact_graph")


# Downgrade Functions: artifacts
def revert_artifacts_table():
    with op.batch_alter_table(ARTIFACTS, schema=None) as batch_op:
        batch_op.drop_column("task_name")
        batch_op.drop_column("plugin_file_id")
        batch_op.drop_column("plugin_snapshot_id")
        batch_op.drop_column("file_size")
        batch_op.drop_column("is_dir")


def drop_foreign_keys_from_artifacts_table():
    with op.batch_alter_table(ARTIFACTS, schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_artifacts_plugin_snapshot_id_plugin_plugin_files"),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f("fk_artifacts_plugin_file_id_plugin_tasks"), type_="foreignkey"
        )


# Downgrade Functions: entry_point_artifact_values
def drop_entry_point_artifact_values_table():
    op.drop_table(ENTRY_POINT_ARTIFACT_VALUES)


def drop_indexes_from_entry_point_artifact_values_table():
    with op.batch_alter_table(ENTRY_POINT_ARTIFACT_VALUES, schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_entry_point_artifact_values_job_resource_id")
        )


def drop_foreign_keys_from_entry_point_artifact_values_table():
    with op.batch_alter_table(ENTRY_POINT_ARTIFACT_VALUES, schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_entry_point_artifact_values_entry_point_resource_snapshot_id_entry_point_artifacts"
            ),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f(
                "fk_entry_point_artifact_values_entry_point_resource_snapshot_id_entry_point_jobs"
            ),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f("fk_entry_point_artifact_values_job_resource_id_resources"),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f("fk_entry_point_artifact_values_value_artifacts"),
            type_="foreignkey",
        )


# Downgrade Functions: function_tasks
def drop_function_tasks_table():
    op.drop_table(FUNCTION_TASKS)


def drop_foreign_keys_from_function_tasks_table():
    with op.batch_alter_table(FUNCTION_TASKS, schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_function_tasks_function_task_id_plugin_tasks"),
            type_="foreignkey",
        )


# Downgrade Functions: entry_point_artifact_output_parameters
def drop_entry_point_artifact_output_parameters_table():
    op.drop_table(ENTRY_POINT_ARTIFACT_OUTPUT_PARAMETERS)


def drop_foreign_keys_from_entry_point_artifact_output_parameters_table():
    with op.batch_alter_table(
        ENTRY_POINT_ARTIFACT_OUTPUT_PARAMETERS, schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_entry_point_artifact_output_parameters_entry_point_resource_snapshot_id_entry_point_artifacts"
            ),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f(
                "fk_entry_point_artifact_output_parameters_plugin_task_parameter_type_resource_snapshot_id_plugin_task_parameter_types"
            ),
            type_="foreignkey",
        )


def drop_indexes_from_entry_point_artifact_output_parameters_table():
    with op.batch_alter_table(
        ENTRY_POINT_ARTIFACT_OUTPUT_PARAMETERS, schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_entry_point_artifact_output_parameters_plugin_task_parameter_type_resource_snapshot_id"
            )
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_entry_point_artifact_output_parameters_entry_point_resource_snapshot_id"
            )
        )


# Downgrade Functions: artifact_tasks
def drop_artifact_tasks_table():
    op.drop_table(ARTIFACT_TASKS)


def drop_foreign_keys_from_artifact_tasks_table():
    with op.batch_alter_table(ARTIFACT_TASKS, schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_artifact_tasks_artifact_task_id_plugin_tasks"),
            type_="foreignkey",
        )


# Downgrade Functions: entry_point_artifacts
def drop_entry_point_artifacts_table():
    op.drop_table(ENTRY_POINT_ARTIFACTS)


def drop_indexes_from_entry_point_artifacts_table():
    with op.batch_alter_table(ENTRY_POINT_ARTIFACTS, schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_entry_point_artifacts_entry_point_resource_snapshot_id")
        )


def drop_foreign_keys_from_entry_point_artifacts_table():
    with op.batch_alter_table(ENTRY_POINT_ARTIFACTS, schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_entry_point_artifacts_entry_point_resource_snapshot_id_entry_points"
            ),
            type_="foreignkey",
        )


# Downgrade Functions: entry_point_artifact_plugins
def drop_entry_point_artifact_plugins_table():
    op.drop_table(ENTRY_POINT_ARTIFACT_PLUGINS)


def drop_foreign_keys_from_entry_point_artifact_plugins_table():
    with op.batch_alter_table(ENTRY_POINT_ARTIFACT_PLUGINS, schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_entry_point_artifact_plugins_entry_point_resource_snapshot_id_entry_points"
            ),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f(
                "fk_entry_point_artifact_plugins_plugin_resource_snapshot_id_plugins"
            ),
            type_="foreignkey",
        )
