"""modifications to support artifact handling

Revision ID: fa39987673e0
Revises: 0ca6eca33569
Create Date: 2025-05-30 09:33:07.080834

"""

from typing import Annotated

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    MappedAsDataclass,
    mapped_column,
    sessionmaker,
)
from sqlalchemy.schema import CreateSequence, DropSequence, Sequence

# revision identifiers, used by Alembic.
revision = "fa39987673e0"
down_revision = "0ca6eca33569"
branch_labels = None
depends_on = None

# database dialects
POSTGRES_DIALECT = "postgresql"

# table names
ARTIFACT_TASKS = "artifact_tasks"
ARTIFACTS = "artifacts"
ENTRY_POINT_ARTIFACT_PARAMETER_OUTPUT_PARAMETERS = (
    "entry_point_artifact_parameter_output_parameters"
)
ENTRY_POINT_ARTIFACT_PARAMETER_VALUES = "entry_point_artifact_parameter_values"
ENTRY_POINT_ARTIFACT_PARAMETERS = "entry_point_artifact_parameters"
ENTRY_POINT_ARTIFACT_PLUGINS = "entry_point_artifact_plugins"
ENTRY_POINT_JOBS = "entry_point_jobs"
ENTRY_POINTS = "entry_points"
FUNCTION_TASKS = "function_tasks"
PLUGIN_PLUGIN_FILES = "plugin_plugin_files"
PLUGIN_TASK_INPUT_PARAMETERS = "plugin_task_input_parameters"
PLUGIN_TASK_OUTPUT_PARAMETERS = "plugin_task_output_parameters"
PLUGIN_TASK_PARAMETER_TYPES = "plugin_task_parameter_types"
PLUGIN_TASKS = "plugin_tasks"
PLUGINS = "plugins"
RESOURCES = "resources"

# sequence names
PLUGIN_TASKS_TASK_ID_SEQ = f"{PLUGIN_TASKS}_task_id_seq"


# Migration data models
intpk = Annotated[
    int,
    mapped_column(sa.BigInteger().with_variant(sa.Integer, "sqlite"), primary_key=True),
]
bigint = Annotated[
    int, mapped_column(sa.BigInteger().with_variant(sa.Integer, "sqlite"))
]
text_ = Annotated[str, mapped_column(sa.Text())]
bool_ = Annotated[bool, mapped_column(sa.Boolean())]


class UpgradeBase(DeclarativeBase, MappedAsDataclass):
    pass


class DowngradeBase(DeclarativeBase, MappedAsDataclass):
    pass


class ArtifactUpgrade(UpgradeBase):
    __tablename__ = ARTIFACTS

    # Database fields
    resource_snapshot_id: Mapped[intpk]
    is_dir: Mapped[bool]


class EntryPointUpgrade(UpgradeBase):
    __tablename__ = ENTRY_POINTS

    # Database fields
    resource_snapshot_id: Mapped[intpk]
    artifact_graph: Mapped[text_]


class PluginTaskUpgrade(UpgradeBase):
    __tablename__ = PLUGIN_TASKS

    # Database fields
    task_id: Mapped[bigint]
    plugin_file_resource_snapshot_id: Mapped[intpk]
    plugin_task_name: Mapped[text_] = mapped_column(primary_key=True)
    type: Mapped[text_]


class FunctionTaskUpgrade(UpgradeBase):
    __tablename__ = FUNCTION_TASKS

    # Database fields
    task_id: Mapped[intpk]


class PluginTaskInputParameterUpgrade(UpgradeBase):
    __tablename__ = PLUGIN_TASK_INPUT_PARAMETERS

    # Database fields
    task_id: Mapped[bigint]
    plugin_file_resource_snapshot_id: Mapped[intpk]
    plugin_task_name: Mapped[text_] = mapped_column(primary_key=True)
    parameter_number: Mapped[intpk]
    name: Mapped[text_] = mapped_column(primary_key=True)


class PluginTaskOutputParameterUpgrade(UpgradeBase):
    __tablename__ = PLUGIN_TASK_OUTPUT_PARAMETERS

    # Database fields
    task_id: Mapped[bigint]
    plugin_file_resource_snapshot_id: Mapped[intpk]
    plugin_task_name: Mapped[text_] = mapped_column(primary_key=True)
    parameter_number: Mapped[intpk]
    name: Mapped[text_] = mapped_column(primary_key=True)


class PluginTaskDowngrade(DowngradeBase):
    __tablename__ = PLUGIN_TASKS

    # Database fields
    task_id: Mapped[intpk]
    plugin_file_resource_snapshot_id: Mapped[bigint]
    plugin_task_name: Mapped[text_]
    type: Mapped[text_]


class PluginTaskInputParameterDowngrade(DowngradeBase):
    __tablename__ = PLUGIN_TASK_INPUT_PARAMETERS

    # Database fields
    task_id: Mapped[intpk]
    plugin_file_resource_snapshot_id: Mapped[bigint]
    plugin_task_name: Mapped[text_]
    parameter_number: Mapped[intpk]
    name: Mapped[text_]


class PluginTaskOutputParameterDowngrade(DowngradeBase):
    __tablename__ = PLUGIN_TASK_OUTPUT_PARAMETERS

    # Database fields
    task_id: Mapped[intpk]
    plugin_file_resource_snapshot_id: Mapped[bigint]
    plugin_task_name: Mapped[text_]
    parameter_number: Mapped[intpk]
    name: Mapped[text_]


def get_sessionmaker():
    bind = op.get_bind()
    return sessionmaker(bind=bind)


def get_database_dialect():
    return op.get_context().dialect.name


# BEGIN: Upgrade
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    create_artifact_tasks_table()
    create_entry_point_artifact_parameter_output_parameters_table()
    create_entry_point_artifact_parameter_values_table()
    create_entry_point_artifact_parameters_table()
    create_entry_point_artifact_plugins_table()
    create_function_tasks_table()

    update_artifacts_table()
    update_entry_points_table()
    update_plugin_task_input_parameters_table()
    update_plugin_task_output_parameters_table()
    update_plugin_tasks_table()

    drop_obsolete_indexes_from_plugin_task_input_parameters_table()
    drop_obsolete_indexes_from_plugin_task_output_parameters_table()

    # Data migrations go here
    next_task_id = migrate_data_upgrade()

    set_non_nullable_columns_in_artifacts_table_upgrade()
    set_non_nullable_columns_in_entry_points_table_upgrade()
    set_non_nullable_columns_in_plugin_task_input_parameters_table_upgrade()
    set_non_nullable_columns_in_plugin_task_output_parameters_table_upgrade()
    set_non_nullable_columns_in_plugin_tasks_table_upgrade()

    change_primary_key_for_plugin_task_input_parameters_table()
    change_primary_key_for_plugin_task_output_parameters_table()
    change_primary_key_for_plugin_tasks_table(next_task_id)

    drop_obsolete_columns_from_plugin_task_input_parameters_table()
    drop_obsolete_columns_from_plugin_task_output_parameters_table()

    add_indexes_to_entry_point_artifact_parameter_output_parameters_table()
    add_indexes_to_entry_point_artifact_parameter_values_table()
    add_indexes_to_entry_point_artifact_parameters_table()
    add_indexes_to_plugin_task_input_parameters_table()
    add_indexes_to_plugin_task_output_parameters_table()
    add_indexes_to_plugin_tasks_table()

    add_foreign_keys_to_artifact_tasks_table()
    add_foreign_keys_to_artifacts_table()
    add_foreign_keys_to_entry_point_artifact_parameter_output_parameters_table()
    add_foreign_keys_to_entry_point_artifact_parameter_values_table()
    add_foreign_keys_to_entry_point_artifact_parameters_table()
    add_foreign_keys_to_entry_point_artifact_plugins_table()
    add_foreign_keys_to_function_tasks_table()
    add_foreign_keys_to_plugin_task_input_parameters_table()
    add_foreign_keys_to_plugin_task_output_parameters_table()
    # ### end Alembic commands ###


# Upgrade Data Migration Functions
def migrate_data_upgrade():
    Session = get_sessionmaker()
    with Session() as session:
        migrate_artifacts_data_upgrade(session)
        migrate_entry_points_data_upgrade(session)
        next_task_id = migrate_plugin_tasks_data_upgrade(session)

        session.commit()

    return next_task_id


def migrate_artifacts_data_upgrade(session):
    stmt = sa.select(ArtifactUpgrade).where(ArtifactUpgrade.is_dir.is_(None))

    for artifact in session.scalars(stmt):
        # Set default values for new columns
        artifact.is_dir = False


def migrate_entry_points_data_upgrade(session):
    stmt = sa.select(EntryPointUpgrade).where(
        EntryPointUpgrade.artifact_graph.is_(None)
    )

    for entry_point in session.scalars(stmt):
        # Set default values for new columns
        entry_point.artifact_graph = ""


def migrate_plugin_tasks_data_upgrade(session):
    task_id = _get_initial_plugin_task_task_id_upgrade(session)
    plugin_task_input_parameters = _get_all_plugin_task_input_parameters_upgrade(
        session
    )
    plugin_task_output_parameters = _get_all_plugin_task_output_parameters_upgrade(
        session
    )

    for plugin_task in _iter_plugin_tasks_upgrade(session):
        # Set default values for new columns
        plugin_task.task_id = task_id
        plugin_task.type = "function"

        _add_task_id_to_plugin_task_parameters_upgrade(
            plugin_task, parameters=plugin_task_input_parameters, task_id=task_id
        )
        _add_task_id_to_plugin_task_parameters_upgrade(
            plugin_task, parameters=plugin_task_output_parameters, task_id=task_id
        )

        function_task = FunctionTaskUpgrade(task_id=task_id)
        session.add(function_task)

        task_id += 1

    return task_id


def _add_task_id_to_plugin_task_parameters_upgrade(plugin_task, parameters, task_id):
    for parameter in parameters:
        if (
            parameter.plugin_file_resource_snapshot_id
            == plugin_task.plugin_file_resource_snapshot_id
        ) and (parameter.plugin_task_name == plugin_task.plugin_task_name):
            parameter.task_id = task_id


def _iter_plugin_tasks_upgrade(session):
    stmt = sa.select(PluginTaskUpgrade).order_by(
        PluginTaskUpgrade.plugin_file_resource_snapshot_id,
        PluginTaskUpgrade.plugin_task_name,
    )
    return session.scalars(stmt)


def _get_initial_plugin_task_task_id_upgrade(session):
    stmt_max_task_id = sa.select(sa.func.max(PluginTaskUpgrade.task_id))
    max_task_id = session.scalar(stmt_max_task_id)
    task_id = int(max_task_id) + 1 if max_task_id is not None else 1
    return task_id


def _get_all_plugin_task_input_parameters_upgrade(session):
    plugin_task_input_parameters_stmt = sa.select(
        PluginTaskInputParameterUpgrade
    ).order_by(
        PluginTaskInputParameterUpgrade.plugin_file_resource_snapshot_id,
        PluginTaskInputParameterUpgrade.plugin_task_name,
        PluginTaskInputParameterUpgrade.parameter_number,
    )
    plugin_task_input_parameters = session.scalars(
        plugin_task_input_parameters_stmt
    ).all()

    return plugin_task_input_parameters


def _get_all_plugin_task_output_parameters_upgrade(session):
    plugin_task_output_parameters_stmt = sa.select(
        PluginTaskOutputParameterUpgrade
    ).order_by(
        PluginTaskOutputParameterUpgrade.plugin_file_resource_snapshot_id,
        PluginTaskOutputParameterUpgrade.plugin_task_name,
        PluginTaskOutputParameterUpgrade.parameter_number,
    )
    plugin_task_output_parameters = session.scalars(
        plugin_task_output_parameters_stmt
    ).all()

    return plugin_task_output_parameters


# Upgrade Functions: plugin_task_output_parameters
def update_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        # "task_id" will become part of the new primary key after data migration
        # is complete
        batch_op.add_column(
            sa.Column(
                "task_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )


def set_non_nullable_columns_in_plugin_task_output_parameters_table_upgrade():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.alter_column("task_id", nullable=False)


def change_primary_key_for_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        # need to manually update the primary key
        batch_op.drop_constraint(
            batch_op.f(
                "fk_plugin_task_output_parameters_plugin_file_resource_snapshot_id_plugin_tasks"
            ),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            constraint_name=batch_op.f("pk_plugin_task_output_parameters"),
            type_="primary",
        )
        batch_op.create_primary_key(
            constraint_name=batch_op.f("pk_plugin_task_output_parameters"),
            columns=["task_id", "parameter_number"],
        )


def add_foreign_keys_to_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_plugin_task_output_parameters_task_id_plugin_tasks"),
            PLUGIN_TASKS,
            ["task_id"],
            ["task_id"],
        )


def add_indexes_to_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_plugin_task_output_parameters_task_id"),
            ["task_id", "name"],
            unique=True,
        )


def drop_obsolete_columns_from_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_column("plugin_task_name")
        batch_op.drop_column("plugin_file_resource_snapshot_id")


def drop_obsolete_indexes_from_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_plugin_task_output_parameters_plugin_file_resource_snapshot_id"
            )
        )


# Upgrade Functions: plugin_task_input_parameters
def update_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        # "task_id" will become the new primary key after data migration is
        # complete
        batch_op.add_column(
            sa.Column(
                "task_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )


def set_non_nullable_columns_in_plugin_task_input_parameters_table_upgrade():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.alter_column("task_id", nullable=False)


def change_primary_key_for_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        # need to manually update the primary key
        batch_op.drop_constraint(
            batch_op.f(
                "fk_plugin_task_input_parameters_plugin_file_resource_snapshot_id_plugin_tasks"
            ),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            constraint_name=batch_op.f("pk_plugin_task_input_parameters"),
            type_="primary",
        )
        batch_op.create_primary_key(
            constraint_name=batch_op.f("pk_plugin_task_input_parameters"),
            columns=["task_id", "parameter_number"],
        )


def add_foreign_keys_to_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_plugin_task_input_parameters_task_id_plugin_tasks"),
            PLUGIN_TASKS,
            ["task_id"],
            ["task_id"],
        )


def add_indexes_to_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_plugin_task_input_parameters_task_id"),
            ["task_id", "name"],
            unique=True,
        )


def drop_obsolete_columns_from_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_column("plugin_task_name")
        batch_op.drop_column("plugin_file_resource_snapshot_id")


def drop_obsolete_indexes_from_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_plugin_task_input_parameters_plugin_file_resource_snapshot_id"
            )
        )


# Upgrade Functions: plugin_tasks
def update_plugin_tasks_table():
    with op.batch_alter_table(PLUGIN_TASKS, schema=None) as batch_op:
        # "task_id" will become the new primary key after data migration is complete
        batch_op.add_column(
            sa.Column(
                "task_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )
        # Nullable will be set to False for "type" after data migration is complete
        batch_op.add_column(sa.Column("type", sa.String(), nullable=True))


def set_non_nullable_columns_in_plugin_tasks_table_upgrade():
    with op.batch_alter_table(PLUGIN_TASKS, schema=None) as batch_op:
        batch_op.alter_column("task_id", nullable=False)
        batch_op.alter_column("type", nullable=False)


def change_primary_key_for_plugin_tasks_table(next_task_id):
    with op.batch_alter_table(PLUGIN_TASKS, schema=None) as batch_op:
        # need to manually handle the addition of a new primary key -- perform after the
        # alter table to allow foreign key relationships to not break
        # creating the index above allows those relationships to continue
        batch_op.drop_constraint(
            constraint_name=batch_op.f("pk_plugin_tasks"), type_="primary"
        )
        batch_op.create_primary_key(
            constraint_name=batch_op.f("pk_plugin_tasks"), columns=["task_id"]
        )

        if get_database_dialect() == POSTGRES_DIALECT:
            batch_op.execute(
                CreateSequence(Sequence(PLUGIN_TASKS_TASK_ID_SEQ, start=next_task_id))
            )
            batch_op.alter_column(
                "task_id",
                server_default=sa.text(
                    f"nextval('{PLUGIN_TASKS_TASK_ID_SEQ}'::regclass)"
                ),
            )


def add_indexes_to_plugin_tasks_table():
    with op.batch_alter_table(PLUGIN_TASKS, schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_plugin_tasks_plugin_file_resource_snapshot_id"),
            ["plugin_file_resource_snapshot_id", "plugin_task_name"],
            unique=True,
        )


# Upgrade Functions: entry_points
def update_entry_points_table():
    with op.batch_alter_table(ENTRY_POINTS, schema=None) as batch_op:
        # Nullable will be set to False for "artifact_graph" after data migration is
        # complete
        batch_op.add_column(sa.Column("artifact_graph", sa.Text(), nullable=True))


def set_non_nullable_columns_in_entry_points_table_upgrade():
    with op.batch_alter_table(ENTRY_POINTS, schema=None) as batch_op:
        batch_op.alter_column("artifact_graph", nullable=False)


# Upgrade Functions: artifacts
def update_artifacts_table():
    with op.batch_alter_table(ARTIFACTS, schema=None) as batch_op:
        # Nullable will be set to False for "is_dir" after data migration is complete
        batch_op.add_column(sa.Column("is_dir", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "file_size",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "plugin_snapshot_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "plugin_file_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("task_name", sa.Text(), nullable=True))


def set_non_nullable_columns_in_artifacts_table_upgrade():
    with op.batch_alter_table(ARTIFACTS, schema=None) as batch_op:
        batch_op.alter_column("is_dir", nullable=False)


def add_foreign_keys_to_artifacts_table():
    with op.batch_alter_table(ARTIFACTS, schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_artifacts_plugin_file_id_plugin_tasks"),
            PLUGIN_TASKS,
            ["plugin_file_id", "task_name"],
            ["plugin_file_resource_snapshot_id", "plugin_task_name"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_artifacts_plugin_snapshot_id_plugin_plugin_files"),
            PLUGIN_PLUGIN_FILES,
            ["plugin_snapshot_id", "plugin_file_id"],
            ["plugin_resource_snapshot_id", "plugin_file_resource_snapshot_id"],
        )


# Upgrade Functions: entry_point_artifact_parameter_values
def create_entry_point_artifact_parameter_values_table():
    op.create_table(
        ENTRY_POINT_ARTIFACT_PARAMETER_VALUES,
        sa.Column(
            "job_resource_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "entry_point_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "artifact_number",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "artifact_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "job_resource_id",
            "entry_point_resource_snapshot_id",
            "artifact_number",
            name=op.f("pk_entry_point_artifact_parameter_values"),
        ),
    )


def add_indexes_to_entry_point_artifact_parameter_values_table():
    with op.batch_alter_table(
        ENTRY_POINT_ARTIFACT_PARAMETER_VALUES, schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entry_point_artifact_parameter_values_job_resource_id"),
            ["job_resource_id", "artifact_number"],
            unique=True,
        )


def add_foreign_keys_to_entry_point_artifact_parameter_values_table():
    with op.batch_alter_table(
        ENTRY_POINT_ARTIFACT_PARAMETER_VALUES, schema=None
    ) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_entry_point_artifact_parameter_values_entry_point_resource_snapshot_id_entry_point_artifact_parameters"
            ),
            ENTRY_POINT_ARTIFACT_PARAMETERS,
            ["entry_point_resource_snapshot_id", "artifact_number"],
            ["entry_point_resource_snapshot_id", "artifact_number"],
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_entry_point_artifact_parameter_values_entry_point_resource_snapshot_id_entry_point_jobs"
            ),
            ENTRY_POINT_JOBS,
            ["entry_point_resource_snapshot_id", "job_resource_id"],
            ["entry_point_resource_snapshot_id", "job_resource_id"],
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_entry_point_artifact_parameter_values_job_resource_id_resources"
            ),
            RESOURCES,
            ["job_resource_id"],
            ["resource_id"],
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_entry_point_artifact_parameter_values_artifact_resource_snapshot_id_artifacts"
            ),
            ARTIFACTS,
            ["artifact_resource_snapshot_id"],
            ["resource_snapshot_id"],
        )


# Upgrade Functions: function_tasks
def create_function_tasks_table():
    op.create_table(
        FUNCTION_TASKS,
        sa.Column(
            "task_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("task_id", name=op.f("pk_function_tasks")),
    )


def add_foreign_keys_to_function_tasks_table():
    with op.batch_alter_table(FUNCTION_TASKS, schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_function_tasks_task_id_plugin_tasks"),
            PLUGIN_TASKS,
            ["task_id"],
            ["task_id"],
        )


# Upgrade Functions: entry_point_artifact_parameter_output_parameters
def create_entry_point_artifact_parameter_output_parameters_table():
    op.create_table(
        ENTRY_POINT_ARTIFACT_PARAMETER_OUTPUT_PARAMETERS,
        sa.Column(
            "entry_point_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "artifact_number",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "parameter_number",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "plugin_task_parameter_type_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint(
            "entry_point_resource_snapshot_id",
            "artifact_number",
            "parameter_number",
            "name",
            name=op.f("pk_entry_point_artifact_parameter_output_parameters"),
        ),
    )


def add_indexes_to_entry_point_artifact_parameter_output_parameters_table():
    with op.batch_alter_table(
        ENTRY_POINT_ARTIFACT_PARAMETER_OUTPUT_PARAMETERS, schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f(
                "ix_entry_point_artifact_parameter_output_parameters_entry_point_resource_snapshot_id"
            ),
            ["entry_point_resource_snapshot_id", "artifact_number", "name"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f(
                "ix_entry_point_artifact_parameter_output_parameters_plugin_task_parameter_type_resource_snapshot_id"
            ),
            ["plugin_task_parameter_type_resource_snapshot_id"],
            unique=False,
        )


def add_foreign_keys_to_entry_point_artifact_parameter_output_parameters_table():
    with op.batch_alter_table(
        ENTRY_POINT_ARTIFACT_PARAMETER_OUTPUT_PARAMETERS, schema=None
    ) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_entry_point_artifact_parameter_output_parameters_entry_point_resource_snapshot_id_entry_point_artifact_parameters"
            ),
            ENTRY_POINT_ARTIFACT_PARAMETERS,
            ["entry_point_resource_snapshot_id", "artifact_number"],
            ["entry_point_resource_snapshot_id", "artifact_number"],
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_entry_point_artifact_parameter_output_parameters_plugin_task_parameter_type_resource_snapshot_id_plugin_task_parameter_types"
            ),
            PLUGIN_TASK_PARAMETER_TYPES,
            ["plugin_task_parameter_type_resource_snapshot_id"],
            ["resource_snapshot_id"],
        )


# Upgrade Functions: artifact_tasks
def create_artifact_tasks_table():
    op.create_table(
        ARTIFACT_TASKS,
        sa.Column(
            "task_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("task_id", name=op.f("pk_artifact_tasks")),
    )


def add_foreign_keys_to_artifact_tasks_table():
    with op.batch_alter_table(ARTIFACT_TASKS, schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_artifact_tasks_task_id_plugin_tasks"),
            PLUGIN_TASKS,
            ["task_id"],
            ["task_id"],
        )


# Upgrade Functions: entry_point_artifact_parameters
def create_entry_point_artifact_parameters_table():
    op.create_table(
        ENTRY_POINT_ARTIFACT_PARAMETERS,
        sa.Column(
            "entry_point_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "artifact_number",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint(
            "entry_point_resource_snapshot_id",
            "artifact_number",
            name=op.f("pk_entry_point_artifact_parameters"),
        ),
    )


def add_indexes_to_entry_point_artifact_parameters_table():
    with op.batch_alter_table(ENTRY_POINT_ARTIFACT_PARAMETERS, schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f(
                "ix_entry_point_artifact_parameters_entry_point_resource_snapshot_id"
            ),
            ["entry_point_resource_snapshot_id", "name"],
            unique=True,
        )


def add_foreign_keys_to_entry_point_artifact_parameters_table():
    with op.batch_alter_table(ENTRY_POINT_ARTIFACT_PARAMETERS, schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_entry_point_artifact_parameters_entry_point_resource_snapshot_id_entry_points"
            ),
            ENTRY_POINTS,
            ["entry_point_resource_snapshot_id"],
            ["resource_snapshot_id"],
        )


# Upgrade Functions: entry_point_artifact_plugins
def create_entry_point_artifact_plugins_table():
    op.create_table(
        ENTRY_POINT_ARTIFACT_PLUGINS,
        sa.Column(
            "entry_point_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "plugin_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "entry_point_resource_snapshot_id",
            "plugin_resource_snapshot_id",
            name=op.f("pk_entry_point_artifact_plugins"),
        ),
    )


def add_foreign_keys_to_entry_point_artifact_plugins_table():
    with op.batch_alter_table(ENTRY_POINT_ARTIFACT_PLUGINS, schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_entry_point_artifact_plugins_entry_point_resource_snapshot_id_entry_points"
            ),
            ENTRY_POINTS,
            ["entry_point_resource_snapshot_id"],
            ["resource_snapshot_id"],
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_entry_point_artifact_plugins_plugin_resource_snapshot_id_plugins"
            ),
            PLUGINS,
            ["plugin_resource_snapshot_id"],
            ["resource_snapshot_id"],
        )


# BEGIN: Downgrade
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    drop_foreign_keys_from_plugin_task_output_parameters_table()
    drop_foreign_keys_from_plugin_task_input_parameters_table()
    drop_foreign_keys_from_function_tasks_table()
    drop_foreign_keys_from_entry_point_artifact_plugins_table()
    drop_foreign_keys_from_entry_point_artifact_parameters_table()
    drop_foreign_keys_from_entry_point_artifact_parameter_values_table()
    drop_foreign_keys_from_entry_point_artifact_parameter_output_parameters_table()
    drop_foreign_keys_from_artifacts_table()
    drop_foreign_keys_from_artifact_tasks_table()

    drop_indexes_from_plugin_tasks_table()
    drop_indexes_from_plugin_task_output_parameters_table()
    drop_indexes_from_plugin_task_input_parameters_table()
    drop_indexes_from_entry_point_artifact_parameters_table()
    drop_indexes_from_entry_point_artifact_parameter_values_table()
    drop_indexes_from_entry_point_artifact_parameter_output_parameters_table()

    restore_columns_dropped_from_plugin_task_output_parameters_table()
    restore_columns_dropped_from_plugin_task_input_parameters_table()

    # Data migrations go here
    migrate_data_downgrade()

    set_non_nullable_columns_in_plugin_task_output_parameters_table_downgrade()
    set_non_nullable_columns_in_plugin_task_input_parameters_table_downgrade()

    revert_primary_key_for_plugin_tasks_table()
    revert_primary_key_for_plugin_task_output_parameters_table()
    revert_primary_key_for_plugin_task_input_parameters_table()

    restore_indexes_dropped_from_plugin_task_output_parameters_table()
    restore_indexes_dropped_from_plugin_task_input_parameters_table()

    revert_plugin_tasks_table()
    revert_plugin_task_output_parameters_table()
    revert_plugin_task_input_parameters_table()
    revert_entry_points_table()
    revert_artifacts_table()

    drop_function_tasks_table()
    drop_entry_point_artifact_plugins_table()
    drop_entry_point_artifact_parameters_table()
    drop_entry_point_artifact_parameter_values_table()
    drop_entry_point_artifact_parameter_output_parameters_table()
    drop_artifact_tasks_table()
    # ### end Alembic commands ###


# Downgrade Data Migration Functions
def migrate_data_downgrade():
    Session = get_sessionmaker()
    with Session() as session:
        migrate_plugin_tasks_data_downgrade(session)

        session.commit()


def migrate_plugin_tasks_data_downgrade(session):
    plugin_task_input_parameters = _get_all_plugin_task_input_parameters_downgrade(
        session
    )
    plugin_task_output_parameters = _get_all_plugin_task_output_parameters_downgrade(
        session
    )

    for plugin_task in _iter_plugin_tasks_downgrade(session):
        if plugin_task.type == "artifact":
            _delete_parameters_with_task_id_downgrade(
                session,
                plugin_task=plugin_task.task_id,
                parameters=plugin_task_input_parameters,
            )
            _delete_parameters_with_task_id_downgrade(
                session,
                plugin_task=plugin_task.task_id,
                parameters=plugin_task_output_parameters,
            )
            session.delete(plugin_task)

        if plugin_task.type == "function":
            _add_plugin_file_resource_snapshot_id_to_plugin_task_parameters_downgrade(
                plugin_task, parameters=plugin_task_input_parameters
            )
            _add_plugin_file_resource_snapshot_id_to_plugin_task_parameters_downgrade(
                plugin_task, parameters=plugin_task_output_parameters
            )


def _delete_parameters_with_task_id_downgrade(session, plugin_task, parameters):
    for parameter in parameters:
        if parameter.task_id == plugin_task.task_id:
            session.delete(parameter)


def _add_plugin_file_resource_snapshot_id_to_plugin_task_parameters_downgrade(
    plugin_task, parameters
):
    for parameter in parameters:
        if parameter.task_id == plugin_task.task_id:
            parameter.plugin_file_resource_snapshot_id = (
                plugin_task.plugin_file_resource_snapshot_id
            )
            parameter.plugin_task_name = plugin_task.plugin_task_name


def _iter_plugin_tasks_downgrade(session):
    stmt = sa.select(PluginTaskDowngrade).order_by(PluginTaskDowngrade.task_id)
    return session.scalars(stmt)


def _get_all_plugin_task_input_parameters_downgrade(session):
    plugin_task_input_parameters_stmt = sa.select(
        PluginTaskInputParameterDowngrade
    ).order_by(
        PluginTaskInputParameterDowngrade.task_id,
        PluginTaskInputParameterDowngrade.parameter_number,
    )
    plugin_task_input_parameters = session.scalars(
        plugin_task_input_parameters_stmt
    ).all()

    return plugin_task_input_parameters


def _get_all_plugin_task_output_parameters_downgrade(session):
    plugin_task_output_parameters_stmt = sa.select(
        PluginTaskOutputParameterDowngrade
    ).order_by(
        PluginTaskOutputParameterDowngrade.task_id,
        PluginTaskOutputParameterDowngrade.parameter_number,
    )
    plugin_task_output_parameters = session.scalars(
        plugin_task_output_parameters_stmt
    ).all()

    return plugin_task_output_parameters


# Downgrade Functions: plugin_task_output_parameters
def revert_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_column("task_id")


def revert_primary_key_for_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        # need to manually update the primary key
        batch_op.drop_constraint(
            constraint_name=batch_op.f("pk_plugin_task_output_parameters"),
            type_="primary",
        )
        batch_op.create_primary_key(
            constraint_name=batch_op.f("pk_plugin_task_output_parameters"),
            columns=["plugin_file_resource_snapshot_id", "plugin_task_name", "name"],
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_plugin_task_output_parameters_plugin_file_resource_snapshot_id_plugin_tasks"
            ),
            PLUGIN_TASKS,
            ["plugin_file_resource_snapshot_id", "plugin_task_name"],
            ["plugin_file_resource_snapshot_id", "plugin_task_name"],
        )


def drop_foreign_keys_from_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_plugin_task_output_parameters_task_id_plugin_tasks"),
            type_="foreignkey",
        )


def drop_indexes_from_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plugin_task_output_parameters_task_id"))


def restore_columns_dropped_from_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("plugin_file_resource_snapshot_id", sa.INTEGER(), nullable=True)
        )
        batch_op.add_column(sa.Column("plugin_task_name", sa.TEXT(), nullable=True))


def restore_indexes_dropped_from_plugin_task_output_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f(
                "ix_plugin_task_output_parameters_plugin_file_resource_snapshot_id"
            ),
            ["plugin_file_resource_snapshot_id", "plugin_task_name", "name"],
            unique=1,
        )


def set_non_nullable_columns_in_plugin_task_output_parameters_table_downgrade():
    with op.batch_alter_table(PLUGIN_TASK_OUTPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.alter_column("plugin_file_resource_snapshot_id", nullable=False)
        batch_op.alter_column("plugin_task_name", nullable=False)


# Downgrade Functions: plugin_task_input_parameters
def revert_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_column("task_id")


def revert_primary_key_for_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        # need to manually update the primary key
        batch_op.drop_constraint(
            constraint_name=batch_op.f("pk_plugin_task_input_parameters"),
            type_="primary",
        )
        batch_op.create_primary_key(
            constraint_name=batch_op.f("pk_plugin_task_input_parameters"),
            columns=["plugin_file_resource_snapshot_id", "plugin_task_name", "name"],
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_plugin_task_input_parameters_plugin_file_resource_snapshot_id_plugin_tasks"
            ),
            PLUGIN_TASKS,
            ["plugin_file_resource_snapshot_id", "plugin_task_name"],
            ["plugin_file_resource_snapshot_id", "plugin_task_name"],
        )


def drop_foreign_keys_from_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_plugin_task_input_parameters_task_id_plugin_tasks"),
            type_="foreignkey",
        )


def drop_indexes_from_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plugin_task_input_parameters_task_id"))


def restore_columns_dropped_from_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("plugin_file_resource_snapshot_id", sa.INTEGER(), nullable=True)
        )
        batch_op.add_column(sa.Column("plugin_task_name", sa.TEXT(), nullable=True))


def restore_indexes_dropped_from_plugin_task_input_parameters_table():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f(
                "ix_plugin_task_input_parameters_plugin_file_resource_snapshot_id"
            ),
            ["plugin_file_resource_snapshot_id", "plugin_task_name", "name"],
            unique=1,
        )


def set_non_nullable_columns_in_plugin_task_input_parameters_table_downgrade():
    with op.batch_alter_table(PLUGIN_TASK_INPUT_PARAMETERS, schema=None) as batch_op:
        batch_op.alter_column("plugin_file_resource_snapshot_id", nullable=False)
        batch_op.alter_column("plugin_task_name", nullable=False)


# Downgrade Functions: plugin_tasks
def revert_plugin_tasks_table():
    with op.batch_alter_table(PLUGIN_TASKS, schema=None) as batch_op:
        batch_op.drop_column("type")
        batch_op.drop_column("task_id")


def revert_primary_key_for_plugin_tasks_table():
    with op.batch_alter_table(PLUGIN_TASKS, schema=None) as batch_op:
        # need to manually handle the change of the primary key
        batch_op.drop_constraint(
            constraint_name=batch_op.f("pk_plugin_tasks"), type_="primary"
        )
        batch_op.create_primary_key(
            constraint_name=batch_op.f("pk_plugin_tasks"),
            columns=["plugin_file_resource_snapshot_id", "plugin_task_name"],
        )

        if get_database_dialect() == POSTGRES_DIALECT:
            batch_op.alter_column("task_id", server_default=None)

    if get_database_dialect() == POSTGRES_DIALECT:
        op.execute(DropSequence(Sequence(PLUGIN_TASKS_TASK_ID_SEQ), if_exists=True))


def drop_indexes_from_plugin_tasks_table():
    with op.batch_alter_table(PLUGIN_TASKS, schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_plugin_tasks_plugin_file_resource_snapshot_id")
        )


# Downgrade Functions: entry_points
def revert_entry_points_table():
    with op.batch_alter_table(ENTRY_POINTS, schema=None) as batch_op:
        batch_op.drop_column("artifact_graph")


# Downgrade Functions: artifacts
def revert_artifacts_table():
    with op.batch_alter_table(ARTIFACTS, schema=None) as batch_op:
        batch_op.drop_column("task_name")
        batch_op.drop_column("plugin_file_id")
        batch_op.drop_column("plugin_snapshot_id")
        batch_op.drop_column("file_size")
        batch_op.drop_column("is_dir")


def drop_foreign_keys_from_artifacts_table():
    with op.batch_alter_table(ARTIFACTS, schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_artifacts_plugin_snapshot_id_plugin_plugin_files"),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f("fk_artifacts_plugin_file_id_plugin_tasks"), type_="foreignkey"
        )


# Downgrade Functions: entry_point_artifact_parameter_values
def drop_entry_point_artifact_parameter_values_table():
    op.drop_table(ENTRY_POINT_ARTIFACT_PARAMETER_VALUES)


def drop_indexes_from_entry_point_artifact_parameter_values_table():
    with op.batch_alter_table(
        ENTRY_POINT_ARTIFACT_PARAMETER_VALUES, schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_entry_point_artifact_parameter_values_job_resource_id")
        )


def drop_foreign_keys_from_entry_point_artifact_parameter_values_table():
    with op.batch_alter_table(
        ENTRY_POINT_ARTIFACT_PARAMETER_VALUES, schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_entry_point_artifact_parameter_values_entry_point_resource_snapshot_id_entry_point_artifact_parameters"
            ),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f(
                "fk_entry_point_artifact_parameter_values_entry_point_resource_snapshot_id_entry_point_jobs"
            ),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f(
                "fk_entry_point_artifact_parameter_values_job_resource_id_resources"
            ),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f(
                "fk_entry_point_artifact_parameter_values_artifact_resource_snapshot_id_artifacts"
            ),
            type_="foreignkey",
        )


# Downgrade Functions: function_tasks
def drop_function_tasks_table():
    op.drop_table(FUNCTION_TASKS)


def drop_foreign_keys_from_function_tasks_table():
    with op.batch_alter_table(FUNCTION_TASKS, schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_function_tasks_task_id_plugin_tasks"),
            type_="foreignkey",
        )


# Downgrade Functions: entry_point_artifact_parameter_output_parameters
def drop_entry_point_artifact_parameter_output_parameters_table():
    op.drop_table(ENTRY_POINT_ARTIFACT_PARAMETER_OUTPUT_PARAMETERS)


def drop_foreign_keys_from_entry_point_artifact_parameter_output_parameters_table():
    with op.batch_alter_table(
        ENTRY_POINT_ARTIFACT_PARAMETER_OUTPUT_PARAMETERS, schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_entry_point_artifact_parameter_output_parameters_entry_point_resource_snapshot_id_entry_point_artifact_parameters"
            ),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f(
                "fk_entry_point_artifact_parameter_output_parameters_plugin_task_parameter_type_resource_snapshot_id_plugin_task_parameter_types"
            ),
            type_="foreignkey",
        )


def drop_indexes_from_entry_point_artifact_parameter_output_parameters_table():
    with op.batch_alter_table(
        ENTRY_POINT_ARTIFACT_PARAMETER_OUTPUT_PARAMETERS, schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_entry_point_artifact_parameter_output_parameters_plugin_task_parameter_type_resource_snapshot_id"
            )
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_entry_point_artifact_parameter_output_parameters_entry_point_resource_snapshot_id"
            )
        )


# Downgrade Functions: artifact_tasks
def drop_artifact_tasks_table():
    op.drop_table(ARTIFACT_TASKS)


def drop_foreign_keys_from_artifact_tasks_table():
    with op.batch_alter_table(ARTIFACT_TASKS, schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_artifact_tasks_task_id_plugin_tasks"),
            type_="foreignkey",
        )


# Downgrade Functions: entry_point_artifact_parameters
def drop_entry_point_artifact_parameters_table():
    op.drop_table(ENTRY_POINT_ARTIFACT_PARAMETERS)


def drop_indexes_from_entry_point_artifact_parameters_table():
    with op.batch_alter_table(ENTRY_POINT_ARTIFACT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_entry_point_artifact_parameters_entry_point_resource_snapshot_id"
            )
        )


def drop_foreign_keys_from_entry_point_artifact_parameters_table():
    with op.batch_alter_table(ENTRY_POINT_ARTIFACT_PARAMETERS, schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_entry_point_artifact_parameters_entry_point_resource_snapshot_id_entry_points"
            ),
            type_="foreignkey",
        )


# Downgrade Functions: entry_point_artifact_plugins
def drop_entry_point_artifact_plugins_table():
    op.drop_table(ENTRY_POINT_ARTIFACT_PLUGINS)


def drop_foreign_keys_from_entry_point_artifact_plugins_table():
    with op.batch_alter_table(ENTRY_POINT_ARTIFACT_PLUGINS, schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_entry_point_artifact_plugins_entry_point_resource_snapshot_id_entry_points"
            ),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f(
                "fk_entry_point_artifact_plugins_plugin_resource_snapshot_id_plugins"
            ),
            type_="foreignkey",
        )
