"""modifications to support artifact handling

Revision ID: fa39987673e0
Revises: 0ca6eca33569
Create Date: 2025-05-30 09:33:07.080834

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fa39987673e0"
down_revision = "0ca6eca33569"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entry_point_artifact_plugins",
        sa.Column(
            "entry_point_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "plugin_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entry_point_resource_snapshot_id"],
            ["entry_points.resource_snapshot_id"],
            name=op.f(
                "fk_entry_point_artifact_plugins_entry_point_resource_snapshot_id_entry_points"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["plugin_resource_snapshot_id"],
            ["plugins.resource_snapshot_id"],
            name=op.f(
                "fk_entry_point_artifact_plugins_plugin_resource_snapshot_id_plugins"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "entry_point_resource_snapshot_id",
            "plugin_resource_snapshot_id",
            name=op.f("pk_entry_point_artifact_plugins"),
        ),
    )
    op.create_table(
        "entry_point_artifacts",
        sa.Column(
            "entry_point_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "artifact_number",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_point_resource_snapshot_id"],
            ["entry_points.resource_snapshot_id"],
            name=op.f(
                "fk_entry_point_artifacts_entry_point_resource_snapshot_id_entry_points"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "entry_point_resource_snapshot_id",
            "artifact_number",
            name=op.f("pk_entry_point_artifacts"),
        ),
    )
    with op.batch_alter_table("entry_point_artifacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entry_point_artifacts_entry_point_resource_snapshot_id"),
            ["entry_point_resource_snapshot_id", "name"],
            unique=True,
        )
    with op.batch_alter_table("plugin_task_input_parameters", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_plugin_task_input_parameters_plugin_file_resource_sn_db04",
            type_="foreignkey",
        )
    with op.batch_alter_table("plugin_task_output_parameters", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_plugin_task_output_parameters_plugin_file_resource_s_3b70",
            type_="foreignkey",
        )

        
    with op.batch_alter_table("plugin_tasks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "task_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=False,
                primary_key=True,
            )
        )   
        batch_op.add_column(sa.Column("type", sa.String(), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_plugin_tasks_plugin_file_resource_snapshot_id"),
            ["plugin_file_resource_snapshot_id", "plugin_task_name"],
            unique=True,
        )

        # need to manually handle the addition of a new primary key -- perform after the
        # alter table to allow foreign key relationships to not break
        # creating the index above allows those relationships to continue
        batch_op.drop_constraint(
            constraint_name=op.f("pk_plugin_tasks"), type_="primary"
        )
        batch_op.create_primary_key(
            constraint_name=op.f("pk_plugin_tasks"), columns=["task_id"]
        )

    op.create_table(
        "artifact_tasks",
        sa.Column(
            "artifact_task_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artifact_task_id"],
            ["plugin_tasks.task_id"],
            name=op.f("fk_artifact_tasks_artifact_task_id_plugin_tasks"),
        ),
        sa.PrimaryKeyConstraint("artifact_task_id", name=op.f("pk_artifact_tasks")),
    )
    op.create_table(
        "entry_point_artifact_output_parameters",
        sa.Column(
            "entry_point_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "artifact_number",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "parameter_number",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "plugin_task_parameter_type_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_point_resource_snapshot_id", "artifact_number"],
            [
                "entry_point_artifacts.entry_point_resource_snapshot_id",
                "entry_point_artifacts.artifact_number",
            ],
            name=op.f(
                "fk_entry_point_artifact_output_parameters_entry_point_resource_snapshot_id_entry_point_artifacts"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["plugin_task_parameter_type_resource_snapshot_id"],
            ["plugin_task_parameter_types.resource_snapshot_id"],
            name=op.f(
                "fk_entry_point_artifact_output_parameters_plugin_task_parameter_type_resource_snapshot_id_plugin_task_parameter_types"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "entry_point_resource_snapshot_id",
            "artifact_number",
            "parameter_number",
            "name",
            name=op.f("pk_entry_point_artifact_output_parameters"),
        ),
    )
    with op.batch_alter_table(
        "entry_point_artifact_output_parameters", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f(
                "ix_entry_point_artifact_output_parameters_entry_point_resource_snapshot_id"
            ),
            ["entry_point_resource_snapshot_id", "artifact_number", "name"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f(
                "ix_entry_point_artifact_output_parameters_plugin_task_parameter_type_resource_snapshot_id"
            ),
            ["plugin_task_parameter_type_resource_snapshot_id"],
            unique=False,
        )

    op.create_table(
        "function_tasks",
        sa.Column(
            "function_task_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["function_task_id"],
            ["plugin_tasks.task_id"],
            name=op.f("fk_function_tasks_function_task_id_plugin_tasks"),
        ),
        sa.PrimaryKeyConstraint("function_task_id", name=op.f("pk_function_tasks")),
    )
    op.create_table(
        "entry_point_artifact_values",
        sa.Column(
            "job_resource_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "entry_point_resource_snapshot_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "artifact_number",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "value",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entry_point_resource_snapshot_id", "artifact_number"],
            [
                "entry_point_artifacts.entry_point_resource_snapshot_id",
                "entry_point_artifacts.artifact_number",
            ],
            name=op.f(
                "fk_entry_point_artifact_values_entry_point_resource_snapshot_id_entry_point_artifacts"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["entry_point_resource_snapshot_id", "job_resource_id"],
            [
                "entry_point_jobs.entry_point_resource_snapshot_id",
                "entry_point_jobs.job_resource_id",
            ],
            name=op.f(
                "fk_entry_point_artifact_values_entry_point_resource_snapshot_id_entry_point_jobs"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["job_resource_id"],
            ["resources.resource_id"],
            name=op.f("fk_entry_point_artifact_values_job_resource_id_resources"),
        ),
        sa.ForeignKeyConstraint(
            ["value"],
            ["artifacts.resource_snapshot_id"],
            name=op.f("fk_entry_point_artifact_values_value_artifacts"),
        ),
        sa.PrimaryKeyConstraint(
            "job_resource_id",
            "entry_point_resource_snapshot_id",
            "artifact_number",
            name=op.f("pk_entry_point_artifact_values"),
        ),
    )
    with op.batch_alter_table("entry_point_artifact_values", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entry_point_artifact_values_job_resource_id"),
            ["job_resource_id", "artifact_number"],
            unique=True,
        )

    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_dir", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("file_size", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "plugin_snapshot_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "plugin_file_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "task_name",
                sa.Text(),
                nullable=True,
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_artifacts_plugin_file_id_plugin_tasks"),
            "plugin_tasks",
            ["plugin_file_id", "task_name"],
            ["plugin_file_resource_snapshot_id", "plugin_task_name"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_artifacts_plugin_snapshot_id_plugin_plugin_files"),
            "plugin_plugin_files",
            ["plugin_snapshot_id", "plugin_file_id"],
            ["plugin_resource_snapshot_id", "plugin_file_resource_snapshot_id"],
        )

    with op.batch_alter_table("entry_points", schema=None) as batch_op:
        batch_op.add_column(sa.Column("artifact_graph", sa.Text(), nullable=False))

    with op.batch_alter_table("plugin_task_input_parameters", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "plugin_task_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=False,
            )
        )
        batch_op.drop_index(
            "ix_plugin_task_input_parameters_plugin_file_resource_snapshot_id"
        )
        # need to manually update the primary key
        batch_op.drop_constraint(
            constraint_name=op.f("pk_plugin_task_input_parameters"), type_="primary"
        )
        batch_op.create_primary_key(
            constraint_name=op.f("pk_plugin_task_input_parameters"),
            columns=["plugin_task_id", "name"],
        )
        batch_op.drop_constraint(
            "fk_plugin_task_input_parameters_plugin_file_resource_snapshot_id_plugin_tasks",
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_plugin_task_input_parameters_plugin_task_id_plugin_tasks"),
            "plugin_tasks",
            ["plugin_task_id"],
            ["task_id"],
        )
        batch_op.drop_column("plugin_task_name")
        batch_op.drop_column("plugin_file_resource_snapshot_id")

    with op.batch_alter_table("plugin_task_output_parameters", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "plugin_task_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=False,
            )
        )
        batch_op.drop_index(
            "ix_plugin_task_output_parameters_plugin_file_resource_snapshot_id"
        )
        # need to manually update the primary key
        batch_op.drop_constraint(
            constraint_name=op.f("pk_plugin_task_output_parameters"), type_="primary"
        )
        batch_op.create_primary_key(
            constraint_name=op.f("pk_plugin_task_output_parameters"),
            columns=["plugin_task_id", "name"],
        )
        batch_op.drop_constraint(
            "fk_plugin_task_output_parameters_plugin_file_resource_snapshot_id_plugin_tasks",
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_plugin_task_output_parameters_plugin_task_id_plugin_tasks"),
            "plugin_tasks",
            ["plugin_task_id"],
            ["task_id"],
        )
        batch_op.drop_column("plugin_task_name")
        batch_op.drop_column("plugin_file_resource_snapshot_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plugin_task_output_parameters", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("plugin_file_resource_snapshot_id", sa.INTEGER(), nullable=False)
        )
        batch_op.add_column(sa.Column("plugin_task_name", sa.TEXT(), nullable=False))
        # need to manually update the primary key
        batch_op.drop_constraint(
            constraint_name=op.f("pk_plugin_task_output_parameters"), type_="primary"
        )
        batch_op.create_primary_key(
            constraint_name=op.f("pk_plugin_task_output_parameters"),
            columns=["plugin_file_resource_snapshot_id", "plugin_task_name", "name"],
        )
        batch_op.drop_constraint(
            batch_op.f("fk_plugin_task_output_parameters_plugin_task_id_plugin_tasks"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_plugin_task_output_parameters_plugin_file_resource_snapshot_id_plugin_tasks",
            "plugin_tasks",
            ["plugin_file_resource_snapshot_id", "plugin_task_name"],
            ["plugin_file_resource_snapshot_id", "plugin_task_name"],
        )
        batch_op.create_index(
            "ix_plugin_task_output_parameters_plugin_file_resource_snapshot_id",
            ["plugin_file_resource_snapshot_id", "plugin_task_name", "name"],
            unique=1,
        )
        batch_op.drop_column("plugin_task_id")

    with op.batch_alter_table("plugin_task_input_parameters", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("plugin_file_resource_snapshot_id", sa.INTEGER(), nullable=False)
        )
        batch_op.add_column(sa.Column("plugin_task_name", sa.TEXT(), nullable=False))
        # need to manually update the primary key
        batch_op.drop_constraint(
            constraint_name=op.f("pk_plugin_task_input_parameters"), type_="primary"
        )
        batch_op.create_primary_key(
            constraint_name=op.f("pk_plugin_task_input_parameters"),
            columns=["plugin_file_resource_snapshot_id", "plugin_task_name", "name"],
        )
        batch_op.drop_constraint(
            batch_op.f("fk_plugin_task_input_parameters_plugin_task_id_plugin_tasks"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_plugin_task_input_parameters_plugin_file_resource_snapshot_id_plugin_tasks",
            "plugin_tasks",
            ["plugin_file_resource_snapshot_id", "plugin_task_name"],
            ["plugin_file_resource_snapshot_id", "plugin_task_name"],
        )
        batch_op.create_index(
            "ix_plugin_task_input_parameters_plugin_file_resource_snapshot_id",
            ["plugin_file_resource_snapshot_id", "plugin_task_name", "name"],
            unique=1,
        )
        batch_op.drop_column("plugin_task_id")

    with op.batch_alter_table("entry_points", schema=None) as batch_op:
        batch_op.drop_column("artifact_graph")

    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_artifacts_plugin_snapshot_id_plugin_plugin_files"),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f("fk_artifacts_plugin_file_id_plugin_tasks"), type_="foreignkey"
        )
        batch_op.drop_column("task_name")
        batch_op.drop_column("plugin_file_id")
        batch_op.drop_column("plugin_snapshot_id")
        batch_op.drop_column("file_size")
        batch_op.drop_column("is_dir")

    with op.batch_alter_table("entry_point_artifact_values", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_entry_point_artifact_values_job_resource_id")
        )

    op.drop_table("entry_point_artifact_values")
    op.drop_table("function_tasks")
    with op.batch_alter_table(
        "entry_point_artifact_output_parameters", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_entry_point_artifact_output_parameters_plugin_task_parameter_type_resource_snapshot_id"
            )
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_entry_point_artifact_output_parameters_entry_point_resource_snapshot_id"
            )
        )

    op.drop_table("entry_point_artifact_output_parameters")
    op.drop_table("artifact_tasks")
    with op.batch_alter_table("entry_point_artifacts", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_entry_point_artifacts_entry_point_resource_snapshot_id")
        )

    with op.batch_alter_table("plugin_tasks", schema=None) as batch_op:
        # need to manually handle the change of the primary key
        batch_op.drop_constraint(
            constraint_name=op.f("pk_plugin_tasks"), type_="primary"
        )
        batch_op.create_primary_key(
            constraint_name=op.f("pk_plugin_tasks"),
            columns=["plugin_file_resource_snapshot_id", "plugin_task_name"],
        )
        batch_op.drop_index(
            batch_op.f("ix_plugin_tasks_plugin_file_resource_snapshot_id")
        )
        batch_op.drop_column("type")
        batch_op.drop_column("task_id")

    op.drop_table("entry_point_artifacts")
    op.drop_table("entry_point_artifact_plugins")
    # ### end Alembic commands ###
